### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by jonschlinkert** [enquirer/enquirer#1]
@TrySound if you have a moment, I'd love to have your feedback on [this code](https://github.com/enquirer/enquirer/blob/master/index.js#L162-L231) in particular. Any feedback would be great, but I'm still somewhat new to promises. 

(@doowb, @tunnckoCore, feedback welcome from you as well)

prs would be great too :) but I'd be happy with feedback.

**Comment by TrySound** [comment]
This part shouldn't be wrapped with Promise. Results can be returned with Promise.resolve and Promise.reject. You still wrap it with try-catch.
https://github.com/enquirer/enquirer/blob/master/index.js#L206-L230

ps Did you try to contribute inquirer? They did a lot of good stuff like introducing Promises.

**Comment by tunnckoCore** [comment]
> This part shouldn't be wrapped with Promise.

The problem isn't that it's wrapped with Promise, but that it is in try catch in that promise.

The `.ask` is okey to me. But I think you can remove try/catch from `.prompt` method. I believe it can be done like that 

```js
var promise = new Promise(function () {
  // the stuff from `try` part
})

return promise.catch(function (err) {
  self.close()
  throw err // to pass it again to the next `.catch`
})
```

**Comment by jonschlinkert** [comment]
> Did you try to contribute inquirer?

yes, we don't agree on goals

**Comment by jonschlinkert** [comment]
ok, thanks I'll review and comment on the rest in a bit, i appreciate it

**Comment by jonschlinkert** [comment]
> what will be used the plugins

for example, I created a plugin that bundles all of the "core" prompt types, so you can just do:

```js
enquirer.use(require('enquirer-prompts'));
```

**Comment by jonschlinkert** [comment]
Hmm, I'm not sure how [this code](https://github.com/enquirer/enquirer/blob/master/index.js#L206-L230) will work consistently if not wrapped in a `new Promise`. We want to make sure we catch errors [here](https://github.com/enquirer/enquirer/blob/master/index.js#L218), or [here](https://github.com/enquirer/enquirer/blob/master/index.js#L208-L216). Am I missing something?

**Comment by tunnckoCore** [comment]
> We want to make sure we catch errors here, or here.

It will work and will catch these cases even without try/catch, try it.

Let's say, that something fails in that `try` block, but not the `PromptType` initialization or `prompt.run` method, it will pass error to `.catch()` or to `.then(null, err)` as usual. If `promptType` or the `.run` method fails it will pass rejected promise to `resolve` and everything is okey.

```js
var promise = new Promise(function (resolve) {
  var rejectedPromise = Promise.reject(new Error('rejected promise'))
  resolve(rejectedPromise)
})

promise.then(console.log, console.error) // => Error: rejected promise
```

**Comment by tunnckoCore** [comment]
As second prompt is pushed - `*-prompt-confirm`, I still believe that we should build them as plugins. And the [index.js#L33](https://github.com/enquirer/enquirer/blob/master/index.js#L33) could be done like this

```js
this.use('input', require('enquirer-prompt-input'))
```

I think we should merge them together and it won't be so breaking change to already created prompts, the changes to them can be minimal as

```js
// here the stuff for
// checkbox class as currently it is

module.exports = function checkBoxPlugin (app) {
    return CheckBoxClass
}
// => enquirer.use('checkbox', require('enquirer-prompt-checkbox'))
```

And `.use` could be changed to this one (error handling added)

```js
Enquirer.prototype.use = function(type, fn) {
  if (utils.isObject(type)) {
    return this.visit('use', type);
  }
  if (typeof type === 'function') {
    fn = type;
    type = null;
  }

  var PromptType = null;

  try {
    PromptType = fn.call(this, this);
  } catch (err) {
    if (err) {
      this.emit('error', err);
      return;
    }
  }

  // maybe we should require `prompts` to
  // have some static property for better detection?
  if (type && typeof ret === 'function') {
    this.prompts[type] = PromptType;
  }

  return this;
};
```
Then in some point in future plugin system can be changed without breaking changes and problems with `use` for example, if more enhanced (or async? or sort of async) plugins is needed.

**Comment by jonschlinkert** [comment]
You might need to talk me through this more, but I don't see why we would want "prompts" and "plugins" to be registered using the same method. They aren't the same thing.  Currently there is a clear "separation of concerns": _Prompts aren't plugins to enquirer, they are instances of `Prompt`._ Plugins are used to extend the instance of enquirer. 

Perhaps we should create another issue to discuss this?

**Comment by jonschlinkert** [comment]
also, it's worth noting that I'm trying to make prompts work without enquirer. It's not 100% there yet, but it should be easy if we keep everything decoupled

**Comment by tunnckoCore** [comment]
> also, it's worth noting that I'm trying to make prompts work without enquirer

I felt it that way too.

> Prompts aren't plugins to enquirer, they are instances of Prompt. 

Yea, absolutely, it's better. Nevermind I just thinking, but you're right.

**Comment by jonschlinkert** [comment]
> Nevermind I just thinking, but you're right.

I love that, it's great. I look forward to your ideas, thanks

**Comment by jonschlinkert** [comment]
ok, I'm going to close but feel free to provide more feedback if you see something that I did wrong or that can be improved. thanks

**Comment by tunnckoCore** [comment]
Nothing more, than suggested Promise changes.

edit: Noticed [that](https://github.com/enquirer/enquirer/blob/master/index.js#L241-L264) know and don't like it. In case you return promise, in another you directly throw errors? Looks like not good feeling.

**Comment by jonschlinkert** [comment]
I thought that's what you were both suggesting to do lol. that's why I was saying it didn't sound right. can you show me what you meant before? (sorry I'm still trying to learn promises. I haven't been a big fan of using them - mainly because I think it increases the learning curve for newcomers, but I still want to learn them, it might change my view...)

**Comment by tunnckoCore** [comment]
Haha, no problem. I don't see what is "the hard" in promises, and why many people don't understand it.
Anyway, maybe I'm really crazy, lol.

I'm thinking for this one

```js
Enquirer.prototype.prompt = function(name) {
  if (Array.isArray(name)) {
    return this.ask.apply(this, arguments);
  }

  this.lazyInit();
  this.queue = this.queue || [name];
  var answers = this.answers;
  var self = this;

  var promise = new Promise(function (resolve, reject) {
    var question = self.question(name).clone();
    var PromptType = self.prompts[question.type];
    var key = question.name;

    if (typeof PromptType !== 'function') {
      var msg = `prompt type "${question.type}" is not registered`;
      return reject(new Error(msg));
    }

    var prompt = new PromptType(question, answers, self.ui);
    if (self.session) prompt.session = true;
    self.emit('prompt', question.default, question, answers, prompt);

    return prompt.run()
      .then(function(answer) {
        answers[key] = question.answer = answer;
        self.emit('answer', answer, key, question, answers);
        return answers;
      });
  });


  return promise.catch(function (err) {
    self.close();
    // we should throw here, because we want
    // user to be able to catch it. By this I mean
    // if you do `app.prompt(...)` and it
    // fails because of something, user would want to
    // do `app.prompt(...).catch()` to handle it, right?
    // So, if you does not throw here, that `.catch` won't
    // be called.
    throw err;
  })
};
```

You can try separately this one to understand the comment in above snippet.

```js
var fs = require('fs')
var readFilePromise = function readFilePromise (fp) {
  return new Promise(function (resolve, reject) {
    fs.readFile(fp, function (err, res) {
      if (err) return reject(err)
      resolve(res)
    })
  })
}

readFilePromise('not-existing')
  .then(
    function onResolved (res) {
      console.log('won`t be called 1')
    },
    function onRejected (err) {
      console.log('would be called 1')
    }
  )
  .catch(function onRejected (err) {
    console.log('won`t be called 1')
  })

// or
readFilePromise('not-existing')
  .catch(function (err) {
    console.log('would be called 2')
  })
  .catch(function (err) {
    console.log('won`t be called 2')
  })
```

Anyway. The whole thing is that you can have more than one listener/handler, so that's why we need to throw from the `.catch`. I found this maybe before one year while building @hybridables. You can see same trick is used in https://github.com/hybridables/then-callback
