### ISSUE TITLE
Option 'defaults' on Snippet not working

### ISSUE THREAD

**Issue by zentek-marco-bruening** [enquirer/enquirer#110]
As in your [example](https://github.com/enquirer/enquirer/blob/master/examples/snippet/option-defaults.js), we can use the *defaults*-option to set the default values. But it is not working.

![grafik](https://user-images.githubusercontent.com/45560978/51188104-964d5400-18dd-11e9-885c-240a0381f292.png)

**Comment by jonschlinkert** [comment]
The example is wrong, thanks for pointing it ou. The correct property name is `values`. Please let me know if that works for you.

**Comment by zentek-marco-bruening** [comment]
Yeah, it works. Thank you
