### ISSUE TITLE
Select value in select from keypress

### ISSUE THREAD

**Issue by Armaldio** [enquirer/enquirer#118]
Is there a way to add something like a shortcut, where you can select a value in a select prompt using a set of keys.

Like I have a select of "Add" and "Remove" and instead of selecting one or the other, I just have to type 'a' to select "Add" or 'r' to select "Remove".

I've tried using keypress event, but it seems i'm not successfull.

**Comment by jonschlinkert** [comment]
The `select` prompt doesn't allow items to be "checked", it only selects the item that the pointer is focused on. 

Try using the [multiselect prompt](https://github.com/enquirer/enquirer#multiselect-prompt). 

- Use <kbd>space</kbd> to toggle the currently focused choice
- Use <kbd>a</kbd> to toggle all choices 
- Use <kbd>i</kbd> to invert all choices
- Use <kbd>g</kbd> to toggle all options in a choice group, when [nested choice groups](https://github.com/enquirer/enquirer/blob/master/examples/multiselect/choice-groups-nested.js) are defined

Is this what you're looking for?

**Comment by Armaldio** [comment]
I don't want to check items, I want to confirm a choice based on a keypress instead of pressing "Enter"

Imagine having: 

![](https://raw.githubusercontent.com/enquirer/enquirer/master/media/select-prompt.gif)

and pressing 'w' select watermellon, whatever the index you are.
It's similar to `number` in [select choice](https://github.com/enquirer/enquirer#select-choices)

**Comment by jonschlinkert** [comment]
Did you try the `autocomplete` prompt?

**Comment by Armaldio** [comment]
Still not really what I'm looking for :/

I think the best way to achieve what I want are [custom prompts](https://github.com/enquirer/enquirer#-custom-prompts) but still I don't know if its doable

**Comment by Armaldio** [comment]
For anyone wondering for a solution, here it is

```js
import { Select } from 'enquirer';

const choices = {
	message: `${chalk.underline('U')}pdate app`,
	name: 7,
	shortcut: 'u',
}

const questions = {
	type: 'select',
	name: 'action',
	message: 'What do you want to do?',
	choices,
	result() {
		return this.focused;
	},
};

prompt = new Select(questions);

prompt.on('keypress', (rawKey) => {
	const foc = prompt.state.choices.find(c => c.shortcut && c.shortcut === rawKey);
	if (foc) {
        prompt.state.index = foc.index;
        prompt.submit();
	}
});

answers = await prompt.run();
```

Maybe (@jonschlinkert) you're also interested in a PR to add this as an example ?

**Comment by jonschlinkert** [comment]
> you're also interested in a PR to add this as an example ?

Yes, that would be great! Thank you!

**Comment by jonschlinkert** [comment]
Closing since I think this is resolved.
