### ISSUE TITLE
Non alpha-numeric characters don't automatically display in the default question (v0.4.1)

### ISSUE THREAD

**Issue by mrozbarry** [enquirer/enquirer#12]
Using a default question, my input flows like this:

1. New prompt, `""`
2. Type a, `"a"`
3. Type -, `"a"`
4. Type b, `"a-b"`

I get the same behaviour with slashes, as well.

**Comment by jonschlinkert** [comment]
related https://github.com/enquirer/readline-utils/issues/2#issuecomment-287588363

**Comment by jonschlinkert** [comment]
I believe this was resolved, I'm going to close but please feel free to reopen or create a new issue if you're still having problems.
