### ISSUE TITLE
How do I avoid adding "initial" to answers when prompt is skipped?

### ISSUE THREAD

**Issue by 3cp** [enquirer/enquirer#120]
```js

prompt([{
  type: 'select',
  message: 'Choice',
  name: 'choice',
  initial: 'a',
  choices: ['a', 'b', 'c'],
  skip: true
}]).then(answers => console.log(answers));
```
It prints `{ choice: 'a' }`, it arguably should be `{}`.
As reference, inquirer doesn't add answer of skipped question.

**Comment by jonschlinkert** [comment]
Is it still answered when you remove `initial`? If you are conditionally enabling `skip`, why not also conditionally remove `initial`?

`skip` is not the same as inquirer's `when`. The point is to give you the ability to skip a question that has already been answered.

**Comment by huochunpeng** [comment]
Thx for the tip. Removing initial results with `{ choice: '' }`.

It seems too verbose to condition both skip and initial.

**Comment by huochunpeng** [comment]
BTW, is this the way (condition both skip and initial) to conditional "remove a question from questionnaire"?

Or is there other official way?

**Comment by jonschlinkert** [comment]
> It seems too verbose to condition both skip and initial.

Agreed, and I'm open to suggestions for how you can skip a question that has already been answered, while also keeping the value. Meaning, the `initial` value is presumably the answer. There might be a better way to do this. 

> Or is there other official way?

No, but I'll be releasing another major version soon, and this would be a good time to make changes if you have ideas.

**Comment by huochunpeng** [comment]
Not sure I can provide good suggestion. Only starting with enquirer/inquirer for few days.

Enquirer’s small foot print is very impressive. That is enough reason for me to choose enquirer.

For the skip, there are two situations:

1. Skip this question because user has provided an explicit/implicit answer.
2. Skip this question because it is irrelevant based on answers of previous questions.

The 2nd situation is what I am try to work out. Not sure whether is good idea to introduce another "when" option, or support a special return value from "skip" option.

**Comment by jonschlinkert** [comment]
Actually, I'm going to reiterate what I mentioned in my first comment, but with an example - because I think this is really easy and not hacky at all. And it should give users the ability to decide which thing they want to do:

```js
const enquirer = require('./');
const someConditionIsMet = true;

const questions = [{
  type: 'input',
  name: 'name',
  message: 'What is your name?',
  initial: 'Jon Schlinkert',
  skip() {
    if (someConditionIsMet) {
      this.initial = void 0;
    }
    return true;
  }
}];

enquirer.prompt(questions)
  .then(console.log)
  .catch(console.error);
```

**Comment by shaunwarman** [comment]
This works for `type: 'input', but not for `type: 'select'` and other `ArrayPrompt` types.

**Comment by vospascal** [comment]
this works 

const questions = [
      {
        type: "select",
        name: "language",
        message: "In what language do you want to create",
        choices: ["Javascript", "Typescript"],
      },
      {
        type: "select",
        name: "create",
        message: "What do you want to create",
        choices: ["component x", "hook y"],
        skip() {
          if (this.state.answers.language === "Javascript") {
            return false;
          }
          return true;
        },
      },
      {
        type: "select",
        name: "create",
        message: "What do you want to create",
        choices: ["component a", "hook b"],
        skip() {
          if (this.state.answers.language === "Typescript") {
            return false;
          }
          return true;
        },
      },
    ];

**Comment by karlhorky** [comment]
One way to avoid having the question names as properties in the `response` object is to use a boolean value and `&&` before a question object:

`index.ts`

```ts
import Enquirer from 'enquirer';
const { prompt } = Enquirer;

const questions = [
  {
    type: 'input',
    name: 'question 1',
    message: 'What is your name?',
  },
  {
    type: 'input',
    name: 'question 2',
    message: 'What is your username?',
    initial: '',
    skip() {
      this.initial = void 0;
      return true;
    },
  },
  false && {
    type: 'input',
    name: 'question 3',
    message: 'What is your username?',
  },
];

const response = await prompt(
  questions.filter(Boolean) as Exclude<(typeof questions)[number], boolean>[],
);

console.log(response);
```

- `"question 2"`, which uses [the `this.initial = void 0` suggestion](https://github.com/enquirer/enquirer/issues/120#issuecomment-468981509) by @jonschlinkert  still shows up as a key in `response`
- `"question 3"` is not present in the object at all

```bash
$ bun index.ts
✔ What is your name? · wf
{
  "question 1": "wf",
  "question 2": undefined,
}
```
