### ISSUE TITLE
Falsy name leads to incorrect return value

### ISSUE THREAD

**Issue by coalpha** [enquirer/enquirer#124]
First of all, amazing package. I love it :)
Okay, so let's say you have some code like this:
```js
const { Select } = require("enquirer");

const fruits = [
  ["Nice", "Apple"],
  ["Moldy", "Kiwi"],
  ["Ripe", "Orange"],
  ["Plump", "Peach"],
  ["Moldy", "Strawberry"]
];
const which = new Select({
  message: "Which fruit?",
  symbols: { indicator: ">" },
  choices: fruits.map(([status, fruit], index) => {
    if (status === "Moldy") {
      return { name: fruit, disabled: true, hint: "(cannot eat moldy fruits)" };
    }
    return { message: fruit, name: index };
  }),
});
(async () => {
  const [status, fruit] = fruits[await which.run()];
  console.log(`Ate a ${status} ${fruit}!`);
})();
```
This code works except if you select `Apple` since the index that's being used as the name is `0`, and `0` is falsy. I haven't read the source code but I'm assuming that enquirer just checks for truthy values. Could enquirer use `{}.hasOwnProperty.call(choice, "name")` instead?

**Comment by jonschlinkert** [comment]
Interesting. I think this is a bug, I'll look into it thanks for letting us know!

**Comment by snowfrogdev** [comment]
I ran into the exact same problem. I'm using a TypeScript enum and the first item in the enum (mapped to 0) is not being processed properly, all the rest are being deat with as expected.

**Comment by Coalpha** [comment]
I'm having a bit of trouble finding the bug.
I think it might be in [lib/types/array.js](https://github.com/enquirer/enquirer/blob/6c2819518a1e2ed284242a99a685655fbaabfa28/lib/types/array.js#L60) but other than that, I don't think I can figure out what's going on.
Sorry I couldn't help more.
