### ISSUE TITLE
Unable to input new value after failed validation in list type

### ISSUE THREAD

**Issue by Means88** [enquirer/enquirer#129]
## Version
2.3.0

## Environment
```console
$ uname -a
Darwin bogon 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

$ zsh --version
zsh 5.3 (x86_64-apple-darwin18.0)

$ node -v
v10.6.0
```

## Reproduction
```js
const { prompt } = require('enquirer');

(async () => {
  const { test } = await prompt({
    type: 'list',
    name: 'test',
    message: 'test',
    validate: v => v.length > 0 ? true : 'should input at least one',
  });
  console.log(test);
})();

```
![screenshot](http://means88.com/statics/tmp/enquirer.gif)

It works well in input type.

**Comment by rajat-sr** [comment]
Thanks, @Means88 for this issue.
Raised PR #187 to resolve it.

**Comment by jjalonso** [comment]
I have still a similar issue.

First time I enter a number value and it fails, after, i try to add other numbers also invalid like "444" but you cannot see anything getting typed, then you press enter and you can see all the numbers appear instantly, and the error too. Look like terminal is not re-rendering.

it neither works when you delete and try to write a valid number, the answer is collected but you cannot see what you typed.

`const response = enquirer.prompt([
  {
    type: 'numeral',
    name: 'entry',
    initial: 1000,
    validate: value => value < 1 ? 'Entry price should be higher!' : true,
    message: 'Entry price?'
  }
]);

response.then(answer => console.log('Answer:', answer));
`


![error-short](https://user-images.githubusercontent.com/389467/66478531-8a6c7800-ea92-11e9-8515-57241d9e26c6.gif)
