### ISSUE TITLE
Getting access to answers as an array of prompts is processed

### ISSUE THREAD

**Issue by sramam** [enquirer/enquirer#131]
In many cases, it's useful to have access to answers to previous prompts when processing validate(), result(), skip(), format().

Perusing the code, it seems that they are passed in (value, state) as arguments - I believe in all cases, but might be mistaken. However, state seems to represent the current state of the active prompt in the sequence. Is there a way to access previous answers of a prompt-array?

**Comment by blikblum** [comment]
I just hit this issue while porting from inquirer.

The answers can be accessed by `state.answers`. Note that sometimes state param is not passed to function in some cases like in `choices` or is passed as first param like in `message`. In this cases it can be accessed using `this.state.answers`

**Comment by sramam** [comment]
thanks @blikblum!
