### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by 318097** [enquirer/enquirer#133]
![Screenshot from 2019-04-16 15-09-33](https://user-images.githubusercontent.com/18000784/56201278-2d04ea80-605e-11e9-8d94-da4843919f57.png)

**Comment by doowb** [comment]
@318097 thanks for the issue!

Can you provide some more information about your environment?

- OS version
- Node.js version
- Terminal
- Anything else that may be helpful

**Comment by 318097** [comment]
This is the info about my system:
![Screenshot from 2019-04-16 17-54-24](https://user-images.githubusercontent.com/18000784/56209506-5f6c1300-6071-11e9-8698-dc74c2ae5bf1.png)

Node.js version: `v8.10.0`
Terminal: I have `zsh` installed. Its version is `zsh 5.4.2 (x86_64-ubuntu-linux-gnu)`
but the problem exists even from normal shell.

**Comment by doowb** [comment]
We determined that this is an configuration setting in `zsh`. I'm going to close this but if anyone else has the same issue, please comment here with information on your environment and example code on how to reproduce.
