### ISSUE TITLE
bugs in example prompts

### ISSUE THREAD

**Issue by 318097** [enquirer/enquirer#136]
## autocomplete
- [ ] How to identify that there is scroll in the list.
- [ ] The scroll is continous. Cannot identify start/end
- [ ] 'option-hightlight.js' => error
- [ ] 'option-multiple.js' => select some option, search for something & press enter

## confirm
- [ ] enquirer-option-default.js, option-istrue.js => error

## editable
- [ ] cannot add numbers in email id (prompt.js)
- [ ] should not accept input if there are errors
- [ ] choices-headings.js => error

## input
- [ ] option-symbol.js => error

## list
- [ ] bug:prompt.js => when the keywords list ends with a 'comma', an empty string is added in the resulting array

## numeral
- [ ] option-initial.js => input is not updated
- [ ] option-format.js => cursor is not in right place during input

## password
- [ ] validation error should be shown while giving input, rather than while submitting

## scale
- [ ] prompt.js => having the scale range starting from 1 would be better

## select
- [ ] option-pointer.js => pointer not shown

## survey 
- [ ] survey:prompt.js => error

**Comment by doowb** [comment]
@318097 thanks for the issue! I'll go through this later today and we can create individual issues around the specific bugs.

**Comment by doowb** [comment]
Moved to separate issues.
