### ISSUE TITLE
autocomplete prompt example

### ISSUE THREAD

**Issue by doowb** [enquirer/enquirer#137]
## autocomplete

- [x] How to identify that there is scroll in the list.
- [x] The scroll is continuous. Cannot identify start/end
- [x] 'option-hightlight.js' => error
- [x] 'option-multiple.js' => select some option, search for something & press enter

**Comment by 318097** [comment]
the highlight() on `options` needs to be updated.

**Comment by doowb** [comment]
> * How to identify that there is scroll in the list.

This can be done by adding a `header` or `footer` function that returns the message specifying there are additional items in the scroll list.

> * The scroll is continuous. Cannot identify start/end

I think this is fine if the first item is addressed (meaning that a user would know it's supposed to scroll). However, if you have any ideas on a good way to indicate this, I'd be happy to hear them.

> * 'option-hightlight.js' => error

As specified above, the `highlight` option right now needs to be a function that returns the function to use. I'm not sure if this is a bug but we came up with a way to update the example to fix this. There will be a PR with that change soon.

> * 'option-multiple.js' => select some option, search for something & press enter

This is a bug and may have been fixed in the [3.0](https://github.com/enquirer/enquirer/tree/3.0) branch. If you'd like to take a look there and port the fix to master, please do.

@318097 If you'd like to make all of the changes for this issue in a single PR, please do and I'll review it.

**Comment by doowb** [comment]
Thanks @318097 for the fixes in #148!
