### ISSUE TITLE
confirm prompt example

### ISSUE THREAD

**Issue by doowb** [enquirer/enquirer#138]
## confirm

The following examples throw errors when running:

- [x] enquirer-option-default.js
- [x] option-istrue.js

**Comment by 318097** [comment]
option-istrue.js: The example prompt overrides the default isTrue() & isFalse() to (t/f) & because of that the (y/N) needs to be updated.

**Comment by doowb** [comment]
> option-istrue.js: The example prompt overrides the default isTrue() & isFalse() to (t/f) & because of that the (y/N) needs to be updated.

I agree. Would you update the example to show how to show `(t/F)` instead of `(y/N)`?
