### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by leebenson** [enquirer/enquirer#14]
Awesome mod. Really love the fact it loads so quickly. I'm wondering if there's a validation option somewhere in the source that I've missed?

Like Inquirer has - if it fails validation, then an error message is displayed and the question is re-asked.

Completely possible to do this in userland, of course, but the code can quickly devolve into spaghetti when separate validation needs to be done inside every `.then` block, with logic to handle the re-prompt.

Apologies if I've missed this; it's not mentioned in the docs.

**Comment by doowb** [comment]
@leebenson thanks for the question. We're still working on getting testing and docs setup for `enquirer` and most of the `prompt-*` modules. Some of the prompts allow passing a `.validate` method when creating the prompt. If you return an error message from `.validate`, this will show under the question (pretty much like inquirer).

I'm going to mark this as "docs" so we can remember to get it documented.

**Comment by jonschlinkert** [comment]
been working on docs, we'll have something up pretty soon

**Comment by RyanZim** [comment]
@jonschlinkert ping?

**Comment by jonschlinkert** [comment]
closing since this library was refactored and this is addressed.
