### ISSUE TITLE
list prompt example

### ISSUE THREAD

**Issue by doowb** [enquirer/enquirer#144]
## list

- [ ] bug:prompt.js => when the keywords list ends with a 'comma', an empty string is added in the resulting array

**Comment by 318097** [comment]
when the input ends with a comma, the answers array contains an empty string. so is it a feature (this is the default functionality of `String.split()`) or a bug?

**Comment by doowb** [comment]
I think the default behavior is fine and if you'd like to create a new example showing how to remove empty strings, that would be awesome.

**Comment by 318097** [comment]
Great. I'll do that.
