### ISSUE TITLE
password prompt example

### ISSUE THREAD

**Issue by 318097** [enquirer/enquirer#145]
## password
- [ ] validation error should be shown while giving input, rather than while submitting

**Comment by jonschlinkert** [comment]
@318097 here is an example of how this can be handled with options:

![2019-04-25 20 06 29](https://user-images.githubusercontent.com/383994/56775582-ae165d00-6795-11e9-81f7-5a4b4eefea0a.gif)

This way you can be as granular as you want, you could even show a different message with every character if you wanted. Let us know if you come up with other ideas for how to do this. I'd love to improve this prompt even more. 

```js
const { Password } = require('enquirer');
const strength = require('prompt-password-strength');

const prompt = new Password({
  name: 'password',
  message: 'What is your password?',
  minLength: 10,
  validate(value = '') {
    let min = this.options.minLength;
    return value.length < min ? `Password must be ${min} or more chars` : true;
  },
  format() {
    this.cursorHide();
    return this.input ? strength(this.input) : '';
  },
  footer() {
    let { pointerSmall, check } = this.symbols;
    let min = this.options.minLength;
    return min - this.input.length > 0
      ? this.styles.danger(`${pointerSmall} password must be ${min} characters or longer`)
      : this.styles.success(`${check} password length is okay`);
  },
});

prompt.run()
  .then(answer => console.log('Answer:', answer))
  .catch(console.error);
```

**Comment by 318097** [comment]
This looks great. I'll see if I got anything more. One change can be, showing the error message when the user stops typing with a delay. Probably, all I can think of is firing the error message method with the help of  `delay()` in `rxjs`

**Comment by doowb** [comment]
Example added in #148
