### ISSUE TITLE
Auto answering

### ISSUE THREAD

**Issue by leebenson** [enquirer/enquirer#15]
The same as this [issue at Inquirer](https://github.com/SBoudrias/Inquirer.js/issues/517#issuecomment-292753130).

Copied for ref:

---

I'm building a CLI tool that takes options via yargs. Inquirer is used to show a 'wizard' for any question that isn't already answered by a command line arg.

I can't use `default`, because that's basically just echoing back what the user has already entered, and is asking them to re-confirm (and if when is false, it gets ignored completely.)

I can't use `when()`, because that will skip the question entirely and avoid populating the answers hash for further questions, as well as miss out on the validation functions.

What would solve it is an `answer` field on the question object. Unlike 'default', putting a value there would avoid asking the question - BUT, it would automatically re-ask it if the value fails validation and show the usual error prompt.

So, it's basically a means to skip asking the question, but treat the value given as the answer.

Does that make sense?

**Comment by doowb** [comment]
@leebenson sorry for not responding to this sooner. I think this is a great idea and with some of the changes that we've discussed will make this easier to do.

Currently, there isn't a way to auto answer and display the answer, but you can fake it by emitting the `line` event when the question is asked:

**Beware: this is a workaround based on how we test the prompts**

```js
const Enquirer = require('enquirer');
const enquirer = new Enquirer();

var answers = {
  color: 'red'
};

enquirer.question('color', {
  type: 'input',
  message: 'What\'s your favorite color?',
  default: 'blue'
});

enquirer.question('size', {
  type: 'input',
  message: 'What\'s your size?',
  default: 'XL'
});

enquirer.on('ask', (prompt) => {
  var answer = answers[prompt.question.name];
  if (typeof answer !== 'undefined') {
    prompt.rl.emit('line', answer);
  }
});

enquirer.ask()
  .then(console.log)
  .catch(console.error);
```

**Comment by ianwalter** [comment]
@doowb That's pretty cool but does it work on other prompts like `list` for example?
