### ISSUE TITLE
problem in saving file

### ISSUE THREAD

**Issue by 318097** [enquirer/enquirer#151]
When I try to save the file, the content gets changed.
![save-issue](https://user-images.githubusercontent.com/18000784/56863870-831c4b00-69d9-11e9-9b23-c1a97637b645.gif)

@doowb Please help me with that
I don't know if this is an issue with my vs code or something to do with markdown

**Comment by doowb** [comment]
That looks like a vs code plugin that's creating a table of contents for the entire file when you save it. Do you have a vs code plugin installed that does something with a markdown TOC?

**Comment by 318097** [comment]
Yes, I have a extension named `Markdown All in One`. I'll try to disable it & check.

**Comment by 318097** [comment]
worked by adding the following setting in vs code 
`  "markdown.extension.toc.updateOnSave": false`
