### ISSUE TITLE
custom prompt example

### ISSUE THREAD

**Issue by rajat-sr** [enquirer/enquirer#169]
- [ ] custom-prompt-standalone.js => error
![image](https://user-images.githubusercontent.com/13731210/60395789-6bd31880-9b56-11e9-9f54-edae94118978.png)
- [ ] custom-prompt-plugin-function.js => error
![image](https://user-images.githubusercontent.com/13731210/60395818-c3718400-9b56-11e9-9f1f-42b66b21fa46.png)

**Comment by doowb** [comment]
@rajat-sr and I spoke about these issues and determined that the examples just need to be updated to align with the latest Enquirer code. He'll be submitting some PRs with the changes.
