### ISSUE TITLE
number and numeral prompt example (option-inital)

### ISSUE THREAD

**Issue by rajat-sr** [enquirer/enquirer#177]
number/option-initial.js _AND_ numeral/option-initial.js => doesn't display characters while typing input
![enquirer-number-initial](https://user-images.githubusercontent.com/13731210/60396641-d2116880-9b61-11e9-9aa9-662642839805.gif)

**Comment by doowb** [comment]
@rajat-sr I figured this out.

[This line in lib/prompt.js](https://github.com/enquirer/enquirer/blob/55923c2e913eeb9d6cfb8d632220145f85aec741/lib/prompt.js#L196) is binding the `this.format` method to ensure the first argument is always using `this.value`.
[This line in lib/types/number.js](https://github.com/enquirer/enquirer/blob/55923c2e913eeb9d6cfb8d632220145f85aec741/lib/types/number.js#L16) initially sets `this.value` and `this.input` to the value of `this.initial`. When `options.initial` is passed in, `this.value` is set, but it's never updated (only `this.input` is updated through `append`, `up`, or `down`).

The quickest fix is to just not set `this.value` initially, then it's never set until `this.submit` is called. If you'd like to submit a PR to change [this line](https://github.com/enquirer/enquirer/blob/55923c2e913eeb9d6cfb8d632220145f85aec741/lib/types/number.js#L16) to `this.input = String(this.initial);`, I think that'll be fine for now.
