### ISSUE TITLE
Windows issue

### ISSUE THREAD

**Issue by stevenvachon** [enquirer/enquirer#19]
This is being logged in AppVeyor CI:
```
V
a
l
u
e
 
f
o
r
 
V
A
R
1
 
(
)
```

from this code:
```js
const Enquirer = require('enquirer');

const test = varnames => {
  const enquirer = new Enquirer();

  const questions = varnames.map(varname => enquirer.question({
    name: varname,
    message: `Value for ${varname}`,
    default: ""
  }));

  return enquirer.ask(questions);
};

test(['VAR1','VAR2']);
```

I'm not sure if what I'm experiencing is caused by Enquirer or by the CI. I've tried running this library in a Windows VM and could not reproduce the issue there.

https://ci.appveyor.com/project/stevenvachon/dotenv-prompt/build/24/job/64gi24d9i6ytyxnf#L588

**Comment by stevenvachon** [comment]
@jonschlinkert @doowb ^^

**Comment by stevenvachon** [comment]
Switched to [node-pty](https://npmjs.com/node-pty) and this issue was resolved, however a whole other can of bugs has been opened, probably unrelated to this library.

**Comment by Vernando05** [comment]
I got this in mintty too
![vertical](https://user-images.githubusercontent.com/4611749/33054279-d1624088-ceaa-11e7-8500-53259082d98f.png),
everything is fine in powershell and cmd

**Comment by jonschlinkert** [comment]
>  I got this in mintty too

Did you create an issue on mintty? Or do you know what is causing the issue and that it's specifically related to this library? If so, please provide all of the details necessary to duplicate the bug and begin debugging so we can solve it.
