### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by jonschlinkert** [enquirer/enquirer#2]
We need a logo!!!

**Comment by aravindjs** [comment]
How about this? ![newlogo](https://cloud.githubusercontent.com/assets/22008758/18252494/6019ee3a-73ac-11e6-8ac0-33d34c32714c.png)

**Comment by jonschlinkert** [comment]
that's headed in the right direction, thanks!

**Comment by jonschlinkert** [comment]
closing since we found a logo a while back
