### ISSUE TITLE
readme incorrectly references prompt-input instead of prompt-text

### ISSUE THREAD

**Issue by sbj42** [enquirer/enquirer#20]
The README.md lists `prompt-input` as a possible prompt type, but [that npm package](https://www.npmjs.com/package/prompt-input) is under a security hold:

> This package name is not currently in use, but was formerly occupied by a popular package. To avoid malicious use, npm is hanging on to the package name, but loosely, and we'll probably give it to you if you want it.

It looks like the actual package included by default in Enquirer is `prompt-text`, so I'm guessing the only issue here is that the README.md needs updating, although it's also not clear if setting the `type` of a question to "input" will choose `prompt-text`.

**Comment by jonschlinkert** [comment]
> The README.md lists prompt-input

Thanks for the heads up! 

Maybe that can be released... If so I'd love to be able to use it.

**Comment by doowb** [comment]
@sbj42 thanks for point this out. We got `prompt-input` and renamed `prompt-text`, so the docs will be correct here. When we make changes to `enquirer`, we'll update to `prompt-input`.
