### ISSUE TITLE
What is the relationship between enquirer and Inquirer.js?

### ISSUE THREAD

**Issue by Gaspacchio** [enquirer/enquirer#205]
I'm writing simple CLI app to ease the integration of style guide in JS projects ([standardize-js](https://github.com/Gaspacchio/standardize-js)), and am currently using [Inquirer.js](https://github.com/SBoudrias/Inquirer.js/) to get an interactive experience. I discovered your project and was wondering if there are benefits to switch from Inquirer.js to enquirer?

I guess issue #22 and #40 are a good start, but could you convince me to switch? Are there any other advantages of one over the other? Is your project capable of delivering the same features?

Furthermore, since both projects seems to pursue the same goal, I was wondering if you were aware of their existence and what was your relationship?

Thanks for your nice answer!

_Btw, I'm going to ask the same question to the Inquirer.js team to get a fair comparison_

**Comment by jonschlinkert** [comment]
There is no relationship. It makes no sense to cross-post the question on Inquirer. This project was created after first attempting to contribute to that library, and the bad attitude and philosophies of the Inquirer team that ensued from that conversation. 

If you want to use Enquirer, great. Or don't.

**Comment by Gaspacchio** [comment]
Sorry if I offended you, it wasn't my intention. I was just seeking to create a great discussion thread that would help people to decide which one would be better to use.

Closing the issue seemed a little harsh to me, I would have loved to be able to get real insights on your advantages and your philosophy!

Thanks in advance and sorry again.

**Comment by jonschlinkert** [comment]
> Sorry if I offended you, it wasn't my intention.

You stated your intentions. 

> Closing the issue seemed a little harsh to me

Issues are reserved for specific feature requests and bug reports. 

> would have loved to be able to get real insights on your advantages and your philosophy!

The advantages and features of Enquirer should be self-evident after reviewing the readme. If not, then download both libraries and use them, then decide which one meets your needs.

**Comment by sw-yx** [comment]
jon has a lot of oss to handle :)

indeed @Gaspacchio you'll be sold if you take a real look at the readme and have tried inquirer before. its not nice to open an issue and say "sell me on this thing", doesn't owe that to you.

**Comment by Gaspacchio** [comment]
Thanks for clarifying things out @sw-yx, it had not occurred to me that it could be bothering to open an issue like this.

I may try the package indeed, thanks for the suggestion. I'm just not used to GitHub issues and thought I could just start a conversation from it.

Thanks again, have a nice day.

**Comment by SBoudrias** [comment]
> This project was created after first attempting to contribute to that library, and the bad attitude and philosophies of the Inquirer team that ensued from that conversation.

Not sure what happened back then, but sorry if you got offended by an answer I gave you. I hope you realize from the follow-up discussion on this thread that as OSS maintainers we're often walking on eggs.

**Comment by Gaspacchio** [comment]
No worries and thanks for your quick answer @SBoudrias!
