### ISSUE TITLE
Select prompt with autocomletion?

### ISSUE THREAD

**Issue by tunnckoCore** [enquirer/enquirer#210]
Like, fuzzy search. I might be lazy but the arrow keys are too far away :D 

The thing is that we will have the list of choices, but should also be able to start typing and what best match to be selected. I think I've seen a similar thing? Anyway, I don't want to use the AutoComplete prompt, because it doesn't show the available choices, which is my intent, so it's easier for end-users calling the cli.

Example code

```js
const { prompt } = require('enquirer');

const answers = {};
function onSubmit(name, value) {
  answers[name] = value;
  return value;
}

async function main() {
  await prompt([
    {
      message: 'Name of the package?',
      type: 'input',
      name: 'name',
      onSubmit,
    },
    {
      message: 'Is it scoped?',
      type: 'toggle',
      name: 'scoped',
      enabled: 'Yes',
      disabled: 'No',
      onSubmit,
    },
    {
      message: 'What is the scope?',
      type: 'select',
      name: 'scope',
      choices: ['@tunnckocore', '@hela'],
      onSubmit,
      skip: () => {
        if (!answers.scoped) {
          answers.location = `packages/${answers.name}`;
          return true;
        }

        return false;
      },
      result: (value) => {
        if (answers.scoped) {
          answers.location = `${value}/${answers.name}`;
          answers.name = answers.location;
          answers.scope = value;
        }
      },
    },
  ]);

  console.log(answers);
}
main();
```

Btw, is there another way to collect answers and be available, when the prompt is triggered? I mean, when the first question is answered I want to be able to see that answer inside the second question and so on. If not, the current solution is okay too.

**Comment by sw-yx** [comment]
related https://github.com/enquirer/enquirer/issues/158

**Comment by tunnckoCore** [comment]
Not exactly. I want to be able to autocomplete from already defined/static choices. Nothing to do with frequency and any form of saving/caching of the choices, which is cool feature anyway :)

**Comment by Whoaa512** [comment]
Isn't this just an [Autocomplete prompt](https://github.com/enquirer/enquirer#autocomplete-prompt)? 

The autocomplete prompt already shows the this of possible choices because it inherits from the Select prompt.

**Comment by tunnckoCore** [comment]
Hm.
