### ISSUE TITLE
Question docked at the bottom?

### ISSUE THREAD

**Issue by linkjay** [enquirer/enquirer#23]
Is there any possible way to dock a question prompt at the bottom or at least move it upon output to the console so it does not interfere with the prompt?

**Comment by jonschlinkert** [comment]
> Is there any possible way to dock a question prompt at the bottom or at least move it upon output to the console so it does not interfere with the prompt?

This is easy to do in [Enquirer 2.0](https://github.com/enquirer/enquirer/pull/24). I'm planning to release it sometime this weekend, Monday at the latest.

**Comment by linkjay** [comment]
Very nice. Since it looks like you already have it done, I will close this.

Thank you!
