### ISSUE TITLE
Autocomplete with multi select

### ISSUE THREAD

**Issue by euberdeveloper** [enquirer/enquirer#242]
I found the module very interesting and more featured than the others. But I think I did not found an alternative to this: https://github.com/faressoft/inquirer-checkbox-plus-prompt

Is there a multiple select which allows autocomplete? If not, please mark the issue as feature requested

**Comment by jonschlinkert** [comment]
Try passing `{ multiple: true }` on the options. I can't remember if this was included in the current release or if it's in the coming release.

**Comment by euberdeveloper** [comment]
> Try passing `{ multiple: true }` on the options. I can't remember if this was included in the current release or if it's in the coming release.

Sorry, did not notice that option. Thank you for the immediate response
