### ISSUE TITLE
Breaks TypeScript Projects

### ISSUE THREAD

**Issue by vasanthdeveloper** [enquirer/enquirer#243]
### 🛠️ What I did
Adding the dependency with the command:
```
npm install enquirer
```
and importing enquirer in the following way:
```
import enquirer from 'enquirer'
```

### 🐛 What happens
Breaks the TypeScript compilation in the following way:
![Isue](https://user-images.githubusercontent.com/24322511/71776353-26d0e880-2fb6-11ea-9057-3f148587a92c.png)

### 🍏 What should happen
The TypeScript should continue compiling without any errors.

----
#### ℹ️ Information
**TypeScript** 3.7.4

**Comment by adityavyas611** [comment]
Hi, @vasanthdeveloper it seems NodeJs.EventEmitter is an interface here, and need implements instead of extends.

Can you please share your code, so I can have a look at the issue?

**Comment by vasanthdeveloper** [comment]
@adityavyas611 Yeah, sure. I am currently working on a private repository. Would you like to get access to it? Right now, I have tested this module locally on my machine. I will create a new branch where we can work on this module.

**Comment by adityavyas611** [comment]
@vasanthdeveloper Yeah sure, please give me the access. so i can have some insights

**Comment by vasanthdeveloper** [comment]
@adityavyas611 I have sent you an invitation to collaborate (which should give you read/push access) to my private repository. Please accept it :smiley:

**Comment by vasanthdeveloper** [comment]
@adityavyas611 Is there any way I can directly chat with you? I use Twitter, Telegram, and Discord.

**Comment by adityavyas611** [comment]
find me on twitter with cybertron611

**Comment by vasanthdeveloper** [comment]
@adityavyas611 I don't think you have DMs enabled on Twitter?

**Comment by unional** [comment]
The reason is described in https://github.com/enquirer/enquirer/pull/246
`NodeJS` is a global namespace, should not be used in a module.

**Comment by vasanthdeveloper** [comment]
@unional Could we close this issue as it is a duplicate of #246 ?

**Comment by unional** [comment]
I'm taking a stab at updating the definition. Adding comments in #135

**Comment by doowb** [comment]
A fix for this has been published in `v2.3.4`.
