### ISSUE TITLE
Cancelling a Select shows the last chosen option

### ISSUE THREAD

**Issue by laggingreflex** [enquirer/enquirer#244]
When using a Select Prompt, the user chooses to cancel (Ctrl+C), it shows the last chosen value anyway:

# Steps to reproduce:

Run the following code:

```
const { Select } = require('enquirer');

const prompt = new Select({
  name: 'color',
  message: 'Pick a flavor',
  choices: ['apple', 'grape', 'watermelon', 'cherry', 'orange']
});

prompt.run()
  .then(answer => console.log('Answer:', answer))
  .catch(console.error);
```

Navigate to any option but don't hit enter

```
? Pick a flavor ...
  apple
  grape
> watermelon
  cherry
  orange
```

Hit Ctrl+C

It will show

```
× Pick a flavor · watermelon
```

It shows the option "watermelon" even though you hit Ctrl+C. 

# Expected behavior 
Nothing should appear
```
× Pick a flavor · 
```
Or like in MultiSelect where it shows "No items were selected" when cancelled.

Tested on Windows 10 CMD.exe, and WSL

**Comment by adityavyas611** [comment]
@laggingreflex could you please share your code, where you are using select prompt?

**Comment by laggingreflex** [comment]
@adityavyas611 I've updated the post with more info.

**Comment by adityavyas611** [comment]
@laggingreflex  please try this and let me know if it works for you

```
const { Select } = require('enquirer');

const prompt = new Select({
  name: 'color',
  message: 'Pick a flavor',
  choices: ['apple', 'grape', 'watermelon', 'cherry', 'orange'],
  format() {
    if (!this.state.submitted || this.state.cancelled) return '';
    if (Array.isArray(this.selected)) {
      return this.selected.map(choice => this.styles.primary(choice.name)).join(', ');
    }
    return this.styles.primary(this.selected.name);
  }
});

prompt.run()
  .then(answer => console.log('Answer:', answer))
  .catch(console.error);
```
![fixselect](https://user-images.githubusercontent.com/6883790/72321775-c125e000-36ca-11ea-9012-c7f4fe692735.gif)

**Comment by laggingreflex** [comment]
@adityavyas611 Yep, that fixes it!
