### ISSUE TITLE
Support for dot notation on `question.name`

### ISSUE THREAD

**Issue by tunnckoCore** [enquirer/enquirer#26]
Seems to not work. But would be great! : ) 

So far, Enquirer v2 is awesome.

**Comment by jonschlinkert** [comment]
It seems like this is something that should be done in implementations, but I'm open to ideas if you have suggestions for how it would be done here.

**Comment by tunnckoCore** [comment]
Oh yea, make total sense. But it would be great if built-in support comes one day.

**Comment by jonschlinkert** [comment]
> it would be great if built-in support comes one day.

Agreed, I'm just not sure of the best approach.  Let me know if you think of a user-friendly way to do it.

**Comment by tunnckoCore** [comment]
The easiest thing is through on submit to be implemented. But.. following example not works as we may expect ;d

```js
enquirer
    .on('submit', (value, item, answers) => {
      setValue(item.answers, item.name, value);
    })
```

In reality, there is no third argument `answers` passed to the submit; and `item.answers` is empty object, which is okey, but it seems that the final return from the `prompt()` call, the "answers" result is not affected, so not depends on this `item.answers`.

**Comment by tunnckoCore** [comment]
Above example is wrong but anyway. 

I think https://github.com/enquirer/enquirer/blob/master/index.js#L125-L130 should return `prompt.state.answers`

**Comment by tunnckoCore** [comment]
Yea, okey, this works

```js
const questions = [{
  type: 'select',
  name: 'commit.type',
  message: 'What is the commit type?',
  choices: commitTypes.map((type) => ({
    message: types[type].title,
    value: type,
  })),
  onSubmit: (key, value, prompt) => {
    setValue(prompt.state.answers, key, value);
  },
},
{
  type: 'input',
  name: 'commit.scope',
  message: 'What is the scope of this change?',
  onSubmit: (key, value, prompt) => {
    setValue(prompt.state.answers, key, value);
  },
}]

console.log(await prompt(questions))
// { 'commit.type': 'feat',
//  commit: { type: 'feat', scope: 'dsadasd' },
//  'commit.scope': 'dsadasd',
```

But sets both the dotted and not dotted one. Won't be a problem anyway.

**Comment by tunnckoCore** [comment]
Probably good idea would be to synchronize the signatures between 

`on('submit')` and the `options.onSubmit`

Currently

```js
function onSubmit(value, { prompt, question }) {
  setValue(prompt.state.answers, question.name, value);
}

enquirer
  .on('submit', onSubmit)
```

and within `options.onSubmit()` is

```js
{
  onSubmit(key, value, prompt) {}
}
```

**Comment by jonschlinkert** [comment]
IMHO, you should set a custom `answers` object:

```js
const answers = {};
const questions = [
  {
    type: 'select',
    name: 'commit.type',
    message: 'What is the commit type?',
    choices: commitTypes.map(type => ({ message: types[type].title, value: type })),
    onSubmit(key, value, prompt) {
      setValue(answers, key, value);
    }
  },
  {
    type: 'input',
    name: 'commit.scope',
    message: 'What is the scope of this change?',
    onSubmit(key, value, prompt) {
      setValue(answers, key, value);
    }
  }
];

console.log(await prompt(questions));
// { 'commit.type': 'feat',
//  commit: { type: 'feat', scope: 'dsadasd' },
//  'commit.scope': 'dsadasd',

```

**Comment by jonschlinkert** [comment]
@tunnckoCore please let me know if you find inconsistencies in the docs or examples. I worked on this for a long time, and I looked at the code so much that I probably overlooked obvious things in the docs.

**Comment by jonschlinkert** [comment]
Closing since I think this was answered and addressed. Please reopen if you want to discuss further.
