### ISSUE TITLE
Multiline prompt?

### ISSUE THREAD

**Issue by tunnckoCore** [enquirer/enquirer#27]
Sounds like there is no such? It errors with "prompt is not registered".

Any way to imitate this?

**Comment by jonschlinkert** [comment]
Thanks for letting us know. Where did you see that one? We are going to re-add it but I thought I removed all of the examples.

**Comment by tunnckoCore** [comment]
> Where did you see that one?

What that? Just needed. Or asking about the error?

**Comment by jonschlinkert** [comment]
wait... oh I see. Lol, we actually had a prompt named `MultiLine` (I think, or it was something similar to that). You obviously meant something different, but that was the first thing that I thought of. 

What error are you getting? Can you show your code?

**Comment by tunnckoCore** [comment]
> I think, or it was something similar to that

Exactly what I want. :D 

> we actually had

When? On v1?

**Comment by tunnckoCore** [comment]
Not only that. 

Lets say we have Snippet prompt with such template

```
<type>[optional scope]: <description>

[optional body]

[optional footer]
```

I think we should support multiline body and multiline footer. It's some work with bypassing the submit.

But anyway, that may be too complex and not so needed. 

Basic multiline prompt would be enough.

**Comment by jonschlinkert** [comment]
> I think we should support multiline body and multiline footer.

It already does (or should). Have you looked through the examples?

**Comment by jonschlinkert** [comment]
@tunnckoCore can you provide an image of something similar? even if it's not a prompt, maybe a mockup or something that works similarly to what you want. I need to have a visual of what you mean.

**Comment by tunnckoCore** [comment]
Yes, try https://www.npmjs.com/package/co-prompt `multiline` prompt and you will see.
I think even Inquirer had such prompt, don't know what's so surprising :P

**Comment by jonschlinkert** [comment]
Oh, I see... A prompt that allows you to intentionally create newline breaks while typing, and only submits after two consecutive returns. Correct?

Yeah, we can do that.

**Comment by jonschlinkert** [comment]
Done. It will be in the next release.

**Comment by tunnckoCore** [comment]
Yea exactly. Great!

**Comment by taktran** [comment]
Hi, I'm trying to do multiline, eg,

I try to paste something like the following into `enquirer` `input`/`form` prompts:

```
Something here

Another line
```

However, the terminal screen gets all messed up with multiple lines of `Something hereAnother line`. It does store the multiline'd content in the response, but without the newlines in there. Is there an example of how this works?

Thanks!
