### ISSUE TITLE
[feature request] Allow programmatical cancellation API

### ISSUE THREAD

**Issue by laggingreflex** [enquirer/enquirer#273]
It'd be awesome if I could cancel the prompt programmatically. 

It seems this ability already exists, but isn't accessible to the user.

**Comment by doowb** [comment]
Enquirer emits a `prompt` event just before starting the prompt (or asking the question). We use this in almost all of the tests to get access to the current `prompt` instance to programmatically control the prompt and simulate user interactions:

```js
const enquirer = new Enquirer();
enquirer.on('prompt', prompt => {
  prompt.cancel();
});

enquirer
  .prompt({ type: 'input', name: 'username', message: 'Username' })
  .then(({ username }) => console.log(username))
  .catch(err => console.error(err));
```

**Comment by vogler** [comment]
Here's what I came up with:
```js
const timeoutPlugin = (timeout = 30) => enquirer => {
  enquirer.on('prompt', prompt => {
    const t = setTimeout(() => { prompt.hint = () => 'timeout'; prompt.cancel(); }, timeout*1000);
    prompt.on('submit', _ => clearTimeout(t));
    prompt.on('cancel', _ => clearTimeout(t));
  });
}
enquirer.use(timeoutPlugin(3)); // timeout after 3s
```
Would be nicer as a prompt option though (for all prompts).
