### ISSUE TITLE
MultiSelect: Pre-check multiple choices

### ISSUE THREAD

**Issue by sqren** [enquirer/enquirer#279]
Hi there,

Coming from [Inquirer.js ](https://github.com/SBoudrias/Inquirer.js) I've been used to pre-checking (pre-selecting) choices with `{"name": "My option", checked: true}`.

I tried the following without luck:

```js
const { MultiSelect } = require("enquirer");

const prompt = new MultiSelect({
  name: "value",
  message: "Pick your favorite colors",
  limit: 7,
  choices: [
    { name: "aqua", checked: false },
    { name: "black", checked: true },
    { name: "blue", checked: true },
  ],
});

prompt.run()
  .then(answer => console.log('Answer:', answer))
  .catch(console.error);
```

**Expected behaviour**
The options "black" and "blue" are pre-checked.

**Actual behaviour**
None of the options are pre-checked.

Is this not yet supported or am I doing it wrong?

**Comment by doowb** [comment]
Hi @sqren, you can use the `enabled` property on a choice. See [the README](https://github.com/enquirer/enquirer#choice-properties) for more information.

**Comment by sqren** [comment]
Hi @doowb 

Sorry for being thick but either there is a bug or the docs are not super clear. Trying the following doesn't pre-check the choice:

```
  const choices = [
    { name: "black", value: "#000000", enabled: true },
    { name: "blue", value: "#0000ff", enabled: false },
  ];

  const prompt = new MultiSelect({
    name: "value",
    message: "Pick your favorite colors",
    choices,
  });

  await prompt.run();
```

I get the following prompt, where I'd expect "black" to be selected:
![image](https://user-images.githubusercontent.com/209966/80967990-87165080-8e17-11ea-92e6-c7edb1e74a4d.png)

**Comment by doowb** [comment]
Ah, yes, this is a bug. There's already an [existing issue](https://github.com/enquirer/enquirer/issues/270) about it. Until that bug is fixed, you can use the `initial` option and pass in either the `name` or `index` of the choices to initially enable:

```js
const choices = [
  { name: "black", value: "#000000" },
  { name: "blue", value: "#0000ff" }
];

const prompt = new MultiSelect({
  name: "value",
  message: "Pick your favorite colors",
  initial: ['black'],
  choices
});

await prompt.run();
```

**Comment by sqren** [comment]
Okay, I'll subscribe to that issue. Thanks
