### ISSUE TITLE
MultiSelect: Returned `answer` should preserve custom properties from `choice`

### ISSUE THREAD

**Issue by sqren** [enquirer/enquirer#280]
Hi there,

Coming from [Inquirer.js ](https://github.com/SBoudrias/Inquirer.js) I've been used to being able to passing `choices` as a list of objects that could contain any custom properties. 

Take this example:

```js
const { MultiSelect } = require("enquirer");

const prompt = new MultiSelect({
  name: "value",
  message: "Pick your favorite colors",
  limit: 7,
  choices: [
    { name: "black", value: "#000000", description: "Black like the night" },
    { name: "blue", value: "#0000ff", description: "Blue like the night" },
    { name: "red", value: "#ff0000", description: "Red like fire" },
  ],
});

prompt
  .run()
  .then((answers) => console.log("Answers:", answers))
  .catch(console.error);

```

**Expected result**
When selecting "blue" and "red", `answers` should be the original choices (including `description` property):
```js
[
  { name: 'blue', value: '#0000ff', description: 'Blue like the night' },
  { name: 'red', value: '#ff0000', description: 'Red like fire' }
]
```

**Actual result**
`answers` is:
```js
[ 'blue', 'red' ]
```

I did try to use `result`:
```js
  result(names) {
    return this.map(names);
  },
```

But that transforms `answers` into:
```js
{ blue: '#0000ff', red: '#ff0000' }
```

Which is not much better (still missing `description`)

How is it possible to preserve the original objects and simply return them as an array?

**Comment by doowb** [comment]
Hi @sqren, the `MultiSelect` prompt is a type of `ArrayPrompt`, which has [these properties](https://github.com/enquirer/enquirer#properties) that can also be used in the `.result` function.

This gives you the option to do something like:

```js
result() {
  return this.selected;
}
```
When used with a `MultiSelect` prompt, this returns an array of enabled `choices`.

**Comment by sqren** [comment]
Great, thanks for that tip.
