### ISSUE TITLE
MultiSelect: `choices` passed to prompt should not be mutated

### ISSUE THREAD

**Issue by sqren** [enquirer/enquirer#281]
_Sorry for the many issues. I'm just excited about this project and interested in improving it_

Hey,

I ran into an issue where enquirer would mutate the `choice` array that is passed to it.

**Example:**
```js
  const choices = [
    { name: "black", value: "#000000" },
    { name: "blue", value: "#0000ff" },
  ];

  const prompt = new MultiSelect({
    name: "value",
    message: "Pick your favorite colors",
    choices,
  });

  await prompt.run();
  console.log(choices); // changed!
```

**Expected behaviour**
`choices` is unchanged.

**Actual behaviour**
Every item in the `choice` array has a bunch of new properties. This seems like implementation details leaking out, and can override identically named properties without the consumer easily realising.

```js
[
  {
    name: "black",
    value: "#000000",
    normalized: true,
    message: "black",
    input: "",
    index: 0,
    cursor: 0,
    level: 1,
    indent: "",
    path: "black",
    enabled: false,
    reset: [Function],
  },
  {
    name: "blue",
    value: "#0000ff",
    normalized: true,
    message: "blue",
    input: "",
    index: 1,
    cursor: 0,
    level: 1,
    indent: "",
    path: "blue",
    enabled: false,
    reset: [Function],
  },
];
```

**Comment by doowb** [comment]
> Sorry for the many issues. I'm just excited about this project and interested in improving it

😀 we're excited about this project too.

Due to current implementation, this is true, however [we're aware](https://github.com/enquirer/enquirer/issues/265) of this and have a fix planned for the next version of `Enquirer`.

Since this is a duplicate, I'll close this issue. Also, thanks for all the excitement for `Enquirer` :)
