### ISSUE TITLE
Is it possible to interrupt or redact a prompt?

### ISSUE THREAD

**Issue by unphased** [enquirer/enquirer#304]
I'm trying to create a CLI tool that periodically runs something. I was originally using my own stdin handling to implement a command dispatch system, but it turned out that enquirer works so well that I decided I want to just build pretty much all user keyboard interaction to leverage enquirer.

The first thing I ran into is that my hand-spun stdin handling loop stops receiving input after enquirer gets activated. I don't know but I think this probably has something to do with enquirer manipulating various things on the stdin stream, such as setting raw mode. This is fine, and I've since dismantled my stdin handling anyway. 

But now comes the conundrum. I'm using a select prompt for a "main menu" interface, this works *beautifully* I might add. But, I have one crucial capability that I need which is to interrupt the menu to run something... Yes, the interaction I'm looking for is kinda outside the scope of a prompt library. But, if there is some way that I can programmatically get the prompt to pick a choice from external to stdin input, that would be really useful in a lot of simple use cases!

**Comment by unphased** [comment]
I'm reading the code and it looks like I might be able to hook events to: listen to prompts being created to get handles to them, and things like that. So maybe it is possible to send some sort of "answer event" to cause a prompt to be answered even without stdin interaction. that would be nice and clean. The main problem is I'd be ok with manually injecting something into stdin to get it to pick an option, but it would invariably pick the wrong option because the user could have fiddled with the cursor beforehand.

**Comment by jonschlinkert** [comment]
> I'm reading the code and it looks like I might be able to hook events to listen to prompts being created to get handles to them, and things like that.

Yes, that's exactly what I was going to suggest. But I don't think you need to do anything to `stdin`. You (probably) just need to call methods on the prompt. 

Try instantiating the `Enquirer` class, then listen for the `prompt` event. Then you can do whatever you need with the prompt instance, even listen for other events on the prompt itself:

```js
const enquirer = new Enquirer();

enquirer.on('prompt', prompt => {
  // do stuff with "prompt" instance
});
```

Inside that listener, you can do whatever you need to the prompt, like `prompt.submit()` or `prompt.cancel()`. I'm not sure what your app looks like, so here is an example of something you could do. 

```js
const Events = require('events');
const enquirer = new Enquirer();
const events = new Events();

enquirer.on('prompt', prompt => {
  // do stuff with "prompt" instance
  events.on('some-event', () => {
    prompt.submit(/* optional value here */);
  });
});
```

**Comment by unphased** [comment]
Thanks a lot for the quick reply! Looking at the entry point from node_modules and also the cloned repo for enquirer I still haven't pieced together how the code all fits together yet. 

Cheers! 🍻

**Comment by unphased** [comment]
@jonschlinkert I have another question, a sort of a followup with this, but an unrelated question.

With this I am able to control a prompt from external to user input when it is active, which is great. Now I want to do even more: provide a little bit of context for something that might run in the background while the code is blocked on an await and the user has a prompt open.

I was hoping I could maybe asynchronously modify the footer contents. I know that Enquirer lets me update the footer (I use the index from context provided in the footer argument to obtain more context from the selected item, it's like a tooltip) when the user switches between options.

Would it be possible to extend the footer functionality somehow to allow for async updating of the footer? 

If not, I could try to use another piece of code to write content to the terminal but it would be difficult to make it not interfere with the active Enquirer prompt that should remain interactive.

**Comment by unphased** [comment]
Sorry I had only skimmed the documentation till now... This may be doable with a custom prompt like with the render method or something... I may be able to replicate the footer behavior and that'd let me do even more than what the footer does...

**Comment by unphased** [comment]
Curiously it looks like it's impossible to check out the enquirer repo and directly run the examples in the examples/ dir...?

**Comment by unphased** [comment]
Wow the examples are really good and answer my question as well as many future questions. This is such a wonderful library. Thank you x1000.
