### ISSUE TITLE
Ability to auto-respond if answer not selected.

### ISSUE THREAD

**Issue by spwoodall** [enquirer/enquirer#325]
This is not a bug, but more of a question/suggestion. (And there may be a way already to accomplish this... if so, an example showing the library's preferred way would be most helpful.) Here's my question:

Is there a built-in way to include a timeout function that would either a) trigger the error catch due to a failure to respond or b) auto-select the first/default answer? (I was looking through your docs and didn't see the general `options` section in the README. I think that this option could be part of the general settings available regardless of prompt type.)

Happy to contribute a solution, too, if that is preferred. I imagine some level of a setTimeout/interval would suffice. Otherwise, a great library and solution!

**Comment by Nigelrex** [comment]
The best thing to add

**Comment by jhicken** [comment]
Just searching the code base. And found there are a couple examples of doing this. That said it would be way more convenient to have this as a top level option.

https://github.com/enquirer/enquirer/blob/8d626c206733420637660ac7c2098d7de45e8590/test/prompt.confirm.js#L113-L120

P.S. I didn't test this.

Just a note that doing this in a linux shell is much simpler. Less readable for sure. 
`read -t10 -p "Would you like to do a thing? (y/n) (wait 10s to skip) " -n 1 -r`

So it would be nice to have a simple timeout and default value option when creating a prompt.
