### ISSUE TITLE
Disable question reprint.

### ISSUE THREAD

**Issue by ladislavjacho** [enquirer/enquirer#331]
First of all, TY for this great tool! I am about to change default behaviour. How can I disable reprinting answers while working with prompt?

![Screenshot 2021-02-01 at 18 44 40](https://user-images.githubusercontent.com/1645758/106496789-9701b480-64bd-11eb-97cc-61d4bf32d9fa.png)

Thanks in advance!

**Comment by ladislavjacho** [comment]
I found out that this issue is bound with nodemon usage. Closing.

**Comment by jonschlinkert** [comment]
Thanks for figuring it out! I was just about to ask for a little more detail.
