### ISSUE TITLE
Space between questions

### ISSUE THREAD

**Issue by mikeerickson** [enquirer/enquirer#333]
This is not a problem with enquirer, but more a question on adding blank grows between groups of questions.

I currently build up an array of questions and then pass that to the problem method.

I would like to insert blank rows between groups of questions?  Is this possible?

Thanks in advance

Mike

**Comment by jonschlinkert** [comment]
> I would like to insert blank rows between groups of questions? Is this possible?

I think you could just use `console.log()` to add a blank row. If that doesn't work let me know, I might be forgetting some nuance in how enquirer clears previous prompts, but I think that should work.

**Comment by jonschlinkert** [comment]
FWIW you can use the events approach to also clear the previous prompt if you want:

```js
enquirer.on('prompt', prompt => {
  prompt.on('submit', () => prompt.clear());
});
```

**Comment by mikeerickson** [comment]
The `console.log` approach fits perfectly in my prompt implementation!

Thank you Jon, appreciate the quick response.
