### ISSUE TITLE
"optoins" mistake 

### ISSUE THREAD

**Issue by alekzonder** [enquirer/enquirer#35]
@jonschlinkert ✋ 

https://github.com/enquirer/enquirer/blob/0473f2e63cbedf8034f06f46d6af26e4727b20e9/lib/prompts/survey.js#L8

and tests pass this

**Comment by jonschlinkert** [comment]
yes, yes I did. I don't know how that got through without eslint throwing a fit. Thanks for the heads up!

**Comment by jonschlinkert** [comment]
fixed! thanks again.
