### ISSUE TITLE
Still Maintained?

### ISSUE THREAD

**Issue by eliellis** [enquirer/enquirer#363]
Seems like many issues and open PRs are unattended and the last commit was quite a while ago. I see there is an [issue asking for a new release into NPM](https://github.com/enquirer/enquirer/issues/347) that has gone unanswered, indicating downstream consumers are a ways off from seeing any updates at this point. Is this project still maintained?

**Comment by jonschlinkert** [comment]
Please read this: https://github.com/jonschlinkert/idiomatic-contributing#dont
