### ISSUE TITLE
Enquirer prevents custom SIGINT handlers from being bound.

### ISSUE THREAD

**Issue by shortercode** [enquirer/enquirer#372]
It's not possible to stop `ctrl +c` from exiting the process if you use an enquirer prompt in your application.

When a prompt is shown the following handler is bound in `prompt.js@60`

```typescript
utils.onExit(() => this.cursorShow());
```

which is intended to restore the cursor if the user exits the process while the prompt is shown. The `onExit` utility intercepts `SIGINT | SIGTERM` events from `process`, performs the callback and then correctly exits the process. However, once the prompt is complete this handler is never removed.

When SIGINT is triggered all callbacks are called in registration order. If any callbacks are registered then Node will not exit automatically. Hence, the standard way to prevent SIGINT from exiting straight away is to register a SIGINT handler to do your cleanup, then call `process.exit` once you are done.

In this case while you can prevent Node from automatically exiting, Enquirer will _always_ exit the process when SIGINT is triggered. Preventing the application from doing any cleanup. If the callback is registered after the Enquirer prompt then it won't even be called.

## Example 1

```typescript
let interrupted = false;
process.on('SIGINT', () => {
  if (interrupted) process.exit();
  interrupted = true;
  console.log('SIGINT');
})
await prompt({
  type: 'input',
  name: 'username',
  message: 'What is your username?'
});
```

1. Run script
2. Enter empty username
3. Press `ctrl + c`

### Expected
Prints SIGINT but doesn't exit process

### Actual
Prints SIGINT and then exits

## Example 2

```typescript
let interrupted = false;
await prompt({
  type: 'input',
  name: 'username',
  message: 'What is your username?'
});
process.on('SIGINT', () => {
  if (interrupted) process.exit();
  interrupted = true;
  console.log('SIGINT');
})
```

1. Run script
2. Enter empty username
3. Press `ctrl + c`

### Expected
Prints SIGINT but doesn't exit process.

### Actual
Just exits.

## Workaround

It's possible to create a stdin rawmode key handler to process the SIGINT event. It must be registered after all prompts have been shown. When in rawmode process does not emit a SIGINT event, preventing the erroneous cleanup code from running.

```typescript
function onRawSIGINT (fn) {
  const { stdin, stdout } = process;
  stdin.setRawMode(true);
  stdin.resume();
  stdin.on('data', (data) => {
    const key = data.toString('utf-8');
    if ( key === '\u0003' ) { // ctrl + c
      fn();
    } else {
      stdout.write(key);
    }
  });
}
```

**Comment by vogler** [comment]
Both examples just exit for me on Ctrl-C without logging SIGINT:

```console
$ node --trace-uncaught enquirer-sigint.js
✖ What is your username? ·

node:internal/process/esm_loader:46
      internalBinding('errors').triggerUncaughtException(
                                ^

Thrown at:
    at loadESM (node:internal/process/esm_loader:46:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


Node.js v20.5.1

$ npm ls | grep enquirer
├── enquirer@2.4.1
```
