### ISSUE TITLE
Typescript not working with built-in prompts - Module 'enquirer' has no exported member 'Select'

### ISSUE THREAD

**Issue by gignupg** [enquirer/enquirer#379]
I was trying to `import { Select } from 'enquirer';` but Typescript doesn't recognize `Select` and throws this error: `Module 'enquirer' has no exported member 'Select'`.
Are types not supported for built-in prompts, or am I doing something wrong?

**Comment by ChiefOfGxBxL** [comment]
Can you try `import Select from 'enquirer';`? That worked for me.

**Comment by ktalebian** [comment]
@ChiefOfGxBxL, `import Select from 'enquirer'` is just importing the default export; you can do `import Whatever from 'enquirer'` and that would work.

It looks like the type definition is very limited: https://github.com/enquirer/enquirer/blob/master/index.d.ts nothing beyond the basic prompt has been exported

**Comment by gignupg** [comment]
@ktalebian I agree, the type definitions seem to be very limited here. I actually decided to switch to [inquirer](https://www.npmjs.com/package/inquirer#methods) instead. They have great TypeScript support once you install their [@types](https://www.npmjs.com/package/@types/inquirer) package.
