### ISSUE TITLE
Use picocolors instead of ansi-colors

### ISSUE THREAD

**Issue by DecliningLotus** [enquirer/enquirer#396]
While I immensely respect @doowb's work on ansi-colors, it's been a never ending arms race for other colour libraries chasing their micro-optimisations in the last couple of years.

[picocolors](https://github.com/alexeyraspopov/picocolors) seems to have won out for now and is used everywhere from Vite to PostCSS and more. The gains are arguably minute, but for a CLI focused project such as this, still be impactful. This should also allow the benchmarks to hit the 3ms range too!

I'd be happy to look into making a PR for this if this is an idea the team is interested in taking.

**Comment by jonschlinkert** [comment]
ansi-colors has 1k more dependents than picocolors, not sure what your metric for "won out" is. More importantly, the reason we use ansi-colors is that it's still highly performant and supports themes. 

thanks for the issue but we're going to stick with ansi-colors to support theming in enquirer.
