### ISSUE TITLE
prompt package names

### ISSUE THREAD

**Issue by jonschlinkert** [enquirer/enquirer#4]
The code is now generalized for questions and prompts (in the `prompt-base` and `prompt-question` modules). 

Since all prompts can now be used with or without enquirer, should I change the naming convention of prompt modules from `enquirer-prompt-*` to just `prompt-*`? 

The only npm name that's taken currently is `prompt-input`, but `input` is built into prompt-base now anyway. 

I'm 50/50 on this (partially b/c I don't look forward to renaming the two or three packages I already published lol), but it seems like making them generic is the way to go - and if so, I should do it now, before I publish the other 5 or 6 modules.

thoughts? @doowb, @tunnckoCore, @trysound?

**Comment by doowb** [comment]
+1 to rename for me. I like the simpler `prompt-`.

**Comment by tunnckoCore** [comment]
Yea, +1 too. And they to stay under the @enquirer org.

**Comment by TrySound** [comment]
+1 prompt and staying

**Comment by jonschlinkert** [comment]
sounds unanimous, I'll start doing that now, thanks for the feedback!
