### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by kevinkhill** [enquirer/enquirer#401]
All the commits are from years ago. All the issues I read are full of promises of getting to things and dealing with them ASAP, but then all get left open. There are more open issues than closed and I am starting to think that [inquirer is the better choice now](https://github.com/SBoudrias/Inquirer.js) since it seems actively maintained.

I'm not trying to be rude, just observing this repo state and the competing library.

IT'S AN AMAZING LIBRARY!!! PEOPLE LOVE IT!!! I LOVE IT!

@doowb @jonschlinkert where are you??

Editing to say, [I get it guys](https://github.com/kevinkhill/lavacharts/blob/3.1/README.md#developer-note=) maintaining an FOSS project is hard.

**Comment by jonschlinkert** [comment]
No
