### ISSUE TITLE
typescript: to infer ReturnType after calling prompt(questions)

### ISSUE THREAD

**Issue by Beraliv** [enquirer/enquirer#411]
## What

When I call `prompt` with `questions`, I want to infer narrowed return type, not just `Promise<object>`.

## Why

All information is available in `name` + `type` + `choices` (if it's enums, tuple or just an array it can be inferred differently)

## Actual result

```ts
import {prompt} from 'enquirer';

// ❌
type PromptResult = Awaited<ReturnType<typeof createBuildPrompt>>;
//   ^? object 

const createBuildPrompt = async () => {
    return prompt([
        {
            type: 'input',
            name: 'username',
            message: 'What is your username?'
        }
    ])
};
```

Playground 🏝️ – https://tsplay.dev/wOxzMN

## Expected Result

```ts
import {prompt} from 'enquirer';

// ✅
type PromptResult = Awaited<ReturnType<typeof createBuildPrompt>>;
//   ^? { username: string } 

const createBuildPrompt = async () => {
    return prompt([
        {
            type: 'input',
            name: 'username',
            message: 'What is your username?'
        }
    ])
};
```

## Other libraries

I've worked with only `yargs` so far, maybe it's worth to add examples of other librarise:

* `yargs` – supports fluent API with `options` and type can be inferred – https://tsplay.dev/mL5LKW ✅
* ...

**Comment by so1ve** [comment]
Though enquirer cannot cautomatically infer return type, you can try:

```ts
prompt<{ username: string }>({ ... })
```

**Comment by wottpal** [comment]
Has there been any progress on this and/or is this planned? Just out of curiosity :)

**Comment by Beraliv** [comment]
> Has there been any progress on this and/or is this planned? Just out of curiosity :)

I decided not to start working on it because it's not clear whether this is the path that this library is leaning towards. If maintainers will be happy this to be implemented, I will happy to contribute

Otherwise, it's easier to use yargs because it supports it
