### ISSUE TITLE
AutoComplete prompt - improve highlighting

### ISSUE THREAD

**Issue by jonschlinkert** [enquirer/enquirer#421]
Currently the `highlight` function only highlights the first matching character in each item. This looks suboptimal when more than one character matches and additional input causes the next match to be highlighted, resulting in the highlighted text "jumping" from one character to later characters on the same line. 

**Solution**

Use something like the following to highlight all matching sequences:

```js
const highlight = (input, color) => {
  const val = input.toLowerCase();
  return str => str.toLowerCase().split(val).join(color(val));
};
```

Also, consider using a different color for highlighted text, by default.

**Comment by adapalmer-okta** [comment]
Hi, I think this change created a bug where typing any kind of regex grouping character causes an error with `new Regex` and immediately terminates the process. Typing [ or ( is enough to trigger it.
