### ISSUE TITLE
Multiselect poor UI

### ISSUE THREAD

**Issue by Maxim-Mazurok** [enquirer/enquirer#424]
Please see https://github.com/nrwl/nx/issues/13916#issuecomment-1358496661 for deaitls

TL;DR I can barely see any color difference and was confused, would prefer if  "√" changed to "x" or similar when item is deselected.
![image](https://github.com/enquirer/enquirer/assets/7756211/282c96b4-4492-49dc-8746-8f4e0f753c17)

**Comment by jonschlinkert** [comment]
Hi @Maxim-Mazurok can you share more information please? 

What terminal?
OS?

Also, there is documentation in the readme for changing the symbol. Here is [an example](https://github.com/enquirer/enquirer/blob/master/examples/multiselect/option-indicator-symbol.js) implementation. There are several others in the examples. 

Thanks!

**Comment by Maxim-Mazurok** [comment]
It's integrated powershell on Windows 10/11 in VS Code in "Light +" theme

I'm going to unsubscribe myself from the thread as this isn't a pressing issue and I have to focus on something else, cheers!

**Comment by srflp** [comment]
Here you have another example, how to change the symbols in enquirer:
https://github.com/pnpm/pnpm/blob/dddb8ad713fd190078edb4715607e6feeef4f12e/pkg-manager/plugin-commands-installation/src/update/index.ts#L212-L251
![Screenshot_20230629_175314](https://github.com/enquirer/enquirer/assets/17103865/2b80b6dd-40bb-4d1c-a88c-f68c9e9121fd)

However, the indicator function has no TS type

**Comment by jonschlinkert** [comment]
> I'm going to unsubscribe myself from the thread as this isn't a pressing issue and I have to focus on something else, cheers!

Sounds good
