### ISSUE TITLE
Skip state is string???

### ISSUE THREAD

**Issue by titsex** [enquirer/enquirer#446]
![image](https://github.com/enquirer/enquirer/assets/61911688/2d790ac1-1a87-48a9-9d92-2bef8b5cd184)
![image](https://github.com/enquirer/enquirer/assets/61911688/43479ca2-a6e5-4b33-87e5-9bffd91a5355)

I don't understand how skip works. Why is it just the name of the current prompt in the state?

**Comment by jonschlinkert** [comment]
Think of `state` as a similar value to what you'd see in Redux action/reducers. 

TBH I don't like how I designed that function, so I agree with your reaction. That said, you should be able to get any property you from the `this` object if you do: 

```js
{
  skip(state) {
    // console.log(this)
  }
}
```

**Comment by titsex** [comment]
> Think of `state` as a similar value to what you'd see in Redux action/reducers.
> 
> TBH I don't like how I designed that function, so I agree with your reaction. That said, you should be able to get any property you from the `this` object if you do:
> 
> ```js
> {
>   skip(state) {
>     // console.log(this)
>   }
> }
> ```

![image](https://github.com/enquirer/enquirer/assets/61911688/4ef69502-b070-40c6-a7cc-ac4ca4225986)
![image](https://github.com/enquirer/enquirer/assets/61911688/c8a287d4-9bd0-4017-bf95-6eac3e28860d)

Now object is empty...

**Comment by titsex** [comment]
And yes, I'm using the latest version.
![image](https://github.com/enquirer/enquirer/assets/61911688/709c7413-f55b-4f7d-93db-8ddd9bd4c4f1)

**Comment by titsex** [comment]
I apologize for the inattention. Skip declared incorrectly. My fault. Thank you.

**Comment by doowb** [comment]
FYI, for anyone that comes across this...

The `skip` function [takes 2 arguments](https://github.com/enquirer/enquirer/blob/70bdb0fedc3ed355d9d8fe4f00ac9b3874f94f61/lib/prompt.js#L196), the name and the value of the prompt.

The README only specifies that `skip` may be a boolean or function. The typescript definition for the `skip` option is not correct.

> Now object is empty...

~The methods and properties on `this` are probably non-enumerable, and won't display in a normal `console.log`.~
I just noticed your `skip` function is a "fat arrow"... so the `this` object is not the prompt, but is something in your code.
