### ISSUE TITLE
enquire.ask twice seems to hang

### ISSUE THREAD

**Issue by matthewmueller** [enquirer/enquirer#5]
Something like this:

``` js
const enquirer = new Enquirer()
enquirer.ask({
  message: 'hi',
  type: 'input',
  name: 'name'
}).then(() => {
  return enquirer.ask({ ... })
})
```

**Comment by jonschlinkert** [comment]
I'm pretty sure I know what's causing that. I have a bunch of fixes to push up for enquirer and some of the prompts. I'll update this as soon as I do

thanks for reporting.

**Comment by jonschlinkert** [comment]
@matthewmueller I believe this was fixed a while ago (and all of the prompts were published), but I forgot to update as promised.
