### ISSUE TITLE
how to access to 'value' in choices?

### ISSUE THREAD

**Issue by kei0719** [enquirer/enquirer#51]
below snippet `select` method  is return  `choices.name` of value, but how can i access to `value` in choices?
```js
const {prompt} = require("enquirer");

(async function() {
  const questions = [
    {
      type: "select",
      name: "color",
      message: "Favorite color?",
      initial: 0,
      choices: [
        {name: "red", message: "red", value: "#ff0000"}, //<= choice object
        {name: "green", message: "Green", value: "#00ff00"}, //<= choice object
        {name: "blue", message: "Blue", value: "#0000ff"} //<= choice object
      ]
    }
  ];

  let answers = await prompt(questions);

 // return choices.name
  console.log(answers.color);   // e.x { color: 'red' }  where's gone ' value ' ??
})();
```

**Comment by jonschlinkert** [comment]
hi @kei0719, thanks for creating an issue. 

I'll show a couple of ways to get the `value` from the selected choice. However, I think we need to make this easier. I'll start working on a better way to get these values.

**onSubmit**

Add an `onSubmit()` function to the question object. The last argument to this function is `prompt`, which is the instance of the prompt that was run for that "question". 

The `prompt.selected` property is a getter with the selected choice (or choices, which `multiple` is true, or the multiselect prompt is used). 

```js
const answers = {};
const questions = [
  {
    type: 'select',
    name: 'color',
    message: 'Favorite color?',
    choices: [
      { name: 'red', message: 'red', value: '#ff0000' }, //<= choice object
      { name: 'green', message: 'Green', value: '#00ff00' }, //<= choice object
      { name: 'blue', message: 'Blue', value: '#0000ff' } //<= choice object
    ],
    onSubmit(name, value, prompt) {
      answers[prompt.selected.name] = prompt.selected.value;
    }
  }
];

await prompt(questions);
console.log(answers); //=> { red: '#ff0000' }
```

Here is an example for how to get values when `multiple` is true:

```js
const answers = {};
const questions = [
  {
    type: 'select',
    name: 'colors',
    message: 'Favorite color?',
    multiple: true,
    choices: [
      { name: 'red', message: 'red', value: '#ff0000' }, //<= choice object
      { name: 'green', message: 'Green', value: '#00ff00' }, //<= choice object
      { name: 'blue', message: 'Blue', value: '#0000ff' } //<= choice object
    ],
    onSubmit(name, value, prompt) {
      let answer = answers[name] = {};
      for (let choice of prompt.selected) {
        answer[choice.name] = choice.value;
      }
    }
  }
];

await prompt(questions);
console.log(answers); //=> { red: '#ff0000', blue: '#0000ff' }
```

Fwiw, the current approach was mostly designed to make it easier to get the values you needed when prompts are used standalone, but I think it will be far more common for users to use  `{ prompt } = require('enquirer')` for running prompts.

**Comment by kei0719** [comment]
I did it what i wanted to do with your way. thanks @jonschlinkert

**Comment by 0x80** [comment]
@jonschlinkert `return this.focused.value;` gives a Typescript error:

> Property 'focused' does not exist on type 'ArrayPromptOptions | BasePromptOptions | BooleanPromptOptions | StringPromptOptions ...

Any idea how to work around that?

Also I'm not sure I understand why the API is the way it is. If you specify a value for the different choices, I would think you always want the value as the returned result. But likely I'm not seeing the full picture here 😄

**Comment by svicalifornia** [comment]
@jonschlinkert  I agree with @0x80 — something seems flawed in how enquirer handles value.

You said in [this comment](https://github.com/enquirer/enquirer/issues/40#issuecomment-437657087):

> Enquirer supports `name`, `value` and `message`. This allows you to use `name` as the "key", `message` to display in the terminal, and `value` is returned in the answer.

But the `value` doesn't get returned as the answer. The `name` of the choice gets returned, and your [code snippet above for choices](#issuecomment-438199121) suggests that we should use the returned `name` value to search the choices array to get the value. This really doesn't make any sense — it's like `value` is totally ignored by enquirer.

**Comment by svicalifornia** [comment]
OK… in version 2.3.0 of enquirer, `this.focused.value` does return the value.

Nonetheless, [your comment on the other thread](https://github.com/enquirer/enquirer/issues/40#issuecomment-437657087) indicates that the question should simply return the `value` of the selected choice, if that choice has a `value` defined. It feels hacky to have to add a result function to every question to access `this.focused.value`.

I understand that this would potentially be a breaking change for some folks, so maybe hold this enhancement for the next major release and advertise it well. But you've already advertised that this is how it should work, and it really would make more sense for `value` to be returned when present.

**Comment by phikes** [comment]
Looks like in ts due to sparsity of exported/declared types we need to do this: 

```
      result(value) {
        return (this as any).map(value)
      },
```
