### ISSUE TITLE
select: value is printed when picked instead of message

### ISSUE THREAD

**Issue by puckey** [enquirer/enquirer#52]
I am using a select, with functions as values:

```javascript
  const { handler } = await prompt({
    name: 'handler',
    type: 'select',
    message: `Question?`,
    choices: [
      {
        message: 'A',
        value: () => {}
      },
      {
        message: 'B',
        value: () => {}
      },
      {
        message: 'C',
        value:  () => {}
      }
    ]
  });

```

 I would expect the message to be printed after the user has picked a choice. Instead I see the function printed to console.

**Comment by jonschlinkert** [comment]
Hi @puckey can you point out where you saw the documentation for how your values were defined so that I can get that fixed? 

Did you try following the conventions shown in the readme, examples, or unit tests?

**Comment by jonschlinkert** [comment]
Try using `name` instead of `message`. 

> because the examples in the readme work differently from those in the examples directory.

I used the examples from the `examples` directory to create the examples in the readme.

**Comment by jonschlinkert** [comment]
also see https://github.com/enquirer/enquirer/issues/51

**Comment by puckey** [comment]
Thanks Jon!
