### ISSUE TITLE
options.initial returns undefined when defined as empty string

### ISSUE THREAD

**Issue by tunnckoCore** [enquirer/enquirer#53]
Probably you should instead check of the existence of that property because currently, it sounds like it checks for falsey value.

```js
const res = await prompt({
  name: 'foo',
  type: 'input',
  message: 'Abc?',
  initial: ''
})
```

**Comment by tunnckoCore** [comment]
It can be fixed temporarily with `onSubmit`

```js
  function onSubmit(value, { prompt, question }) {
    if ('initial' in question && !value) {
      value = question.initial;
    }
    setValue(prompt.state.answers, question.name, value);
  }
```

**Comment by jonschlinkert** [comment]
What do you mean "cannot be an empty string"? Are you getting an error? It works fine for me.

**Comment by tunnckoCore** [comment]
No. It sets it to `undefined` in the answers final result and in the `onSubmit` the `value` is `undefined` too.

**Comment by jonschlinkert** [comment]
> No. It sets it to `undefined` in the answers final result and in the `onSubmit` the `value` is `undefined` too.

Got it, definitely a bug. Want to do a pr?
