### ISSUE TITLE
"await" doesnt work

### ISSUE THREAD

**Issue by c0ncentus** [enquirer/enquirer#58]
I install with npm i enquirer (nodejs V8.12.0)

![image](https://user-images.githubusercontent.com/25374826/48484589-ceb9ae80-e816-11e8-850f-e5a65197c679.png)

i want to put this module in my project, its pretty nice !!! 👍 

PS : With .ts i cant go very far so now i will use enquirer with .js 😭 
Good luck 😃

**Comment by tiphedor** [comment]
You need to wrap you code inside an async function:
````js
async function foo() {
    const response = await prompt(...)
}
foo()
````

See: https://javascript.info/async-await
