### ISSUE TITLE
Formatting result of autocomplete

### ISSUE THREAD

**Issue by paidit-app** [enquirer/enquirer#67]
I have been trying to format the result of an **autocomplete** prompt, by adding the following function:
```
result(value) {
    return `origin/${value}`;
}
```
but it doesn't seem to change anything.

I tried searching for a related issue or read the source code, but all I found is it's possible to override the **format** function, which will give me the result I want, but mess with the input.
I am probably missing something, so I would really appreciate any help in the matter.

**Comment by paidit-app** [comment]
Oh cool, thanks. Looking forward to the new version :)

**Comment by jonschlinkert** [comment]
@paidit-app please try installing the latest version and see if that fixes your problem. Sorry this took so long!

**Comment by paidit-app** [comment]
We just upgraded to the new version and everything seems to work very well. Thank you!
