### ISSUE TITLE
Invalid `process.stdin` stream when test with Ava

### ISSUE THREAD

**Issue by IniZio** [enquirer/enquirer#68]
I am moving from prompts to enquirer. Previously with prompts I can use `.inject` to replace user input, but I don't see such method on enquirer. 

This seems to become a problem with Ava because Ava runs tests in parallel, so when I try to run test with enquirer as follows:

```js
clipped.prompt.on('prompt', (p: any) => {
  p.value = 'a2'
  p.submit()
})

const response = await clipped.prompt({
  type: 'text',
  name: 'q1',
  initial: 'a1',
  message: 'Question 1'
})
t.is(response.q1, 'a2')
```
It will return error `Error: Invalid stream passed`

**Comment by jonschlinkert** [comment]
> I am moving from prompts to enquirer.

That's great! Sorry for the late reply, I was on holiday for Thanksgiving. 

I'm not familiar with Ava, but I think we can get this figured out. First, can you share more details about how you're initializing Enquirer?

In the meantime, try instantiating Enquirer with an `answers` object:

```js
const enquirer = new Enquirer(options, answers);
```

If the values you want to use are on the `answers` object provided to the constructor (even if the values are added later, by reference), you can use the `autofill` option to have Enquirer skip a question when an answer already exists. 

```js
const enquirer = new Enquirer({ autofill: true }, answers);
```

Hope that makes sense. I have a lot more documentation finished, I'll be pushing it up very soon after I get it more organized.

**Comment by IniZio** [comment]
Hi, really grateful to receive your reply :smile: ,

Currently It seems like `process.stdin` passed in to Enquirer is incorrect. The error stack is as follows:

```bash
  Unhandled rejection in dist/test/helper.test.js

  /home/iniz/magic/clipped/node_modules/enquirer/lib/keypress.js:191

  Error: Invalid stream passed

  Function.keypress.listen (/home/iniz/magic/clipped/node_modules/enquirer/lib/keypress.js:191:11)
  StringPrompt.start (/home/iniz/magic/clipped/node_modules/enquirer/lib/prompt.js:158:28)
  StringPrompt.initialize (/home/iniz/magic/clipped/node_modules/enquirer/lib/prompt.js:167:16)
  Promise (/home/iniz/magic/clipped/node_modules/enquirer/lib/prompt.js:179:18)
  StringPrompt.run (/home/iniz/magic/clipped/node_modules/enquirer/lib/prompt.js:176:12)
  Enquirer.prompt (/home/iniz/magic/clipped/node_modules/enquirer/index.js:118:30)
  Clipped.fn [as prompt] (/home/iniz/magic/clipped/node_modules/enquirer/index.js:220:23)
  test/helper.test.ts:61:34
  step (dist/test/helper.test.js:124:17)
```
It is also pushed to https://github.com/clippedjs/clipped/tree/enquirer, running `yarn && lerna run test` will run the test cases.

**Comment by jonschlinkert** [comment]
@IniZio can you point me to the place in the code where Enquirer is required in and/or added to the `clipped` instance? I can't find it.

**Comment by IniZio** [comment]
This is where Enquirer is assigned to `clipped` https://github.com/clippedjs/clipped/blob/enquirer/packages/clipped/src/instance/helper.ts#L123

And this is the test case: https://github.com/clippedjs/clipped/blob/enquirer/packages/clipped/test/helper.test.ts#L55-L66

**Comment by IniZio** [comment]
Many thanks for your help, since it is probably not a problem with Enquirer I will close this issue. Will post the answer here though if i do find it.

Thanks again for this awesome library you made :smile:
