### ISSUE TITLE
feat: multiselect similar to vue-cli

### ISSUE THREAD

**Issue by mikeerickson** [enquirer/enquirer#69]
I am curious if the `multiselect` type has ability to use an interface like vue-cli and other various cli tools

![image](https://user-images.githubusercontent.com/183153/48789346-aeb83e00-eca1-11e8-88d6-2d45e13fb91a.png)

**Comment by doowb** [comment]
Yes, I added [this example](https://github.com/enquirer/enquirer/blob/master/examples/multiselect/option-pointer-indicator.js) showing how to make the `multiselect` look like that:

![image](https://user-images.githubusercontent.com/995160/48791660-36ad4080-ecc0-11e8-9555-e11ada27cd52.png)


```js
'use strict';

const colors = require('ansi-colors');
const { MultiSelect } = require('enquirer');

const prompt = new MultiSelect({
  name: 'food',
  message: 'What are your favorite foods?',
  choices: [
    { name: 'lasagna', message: 'Lasagna' },
    { name: 'pizza', message: 'Pizza' },
    { name: 'chicken_curry', message: 'Chicken Curry' },
    { name: 'tacos', message: 'Tacos' }
  ],
  pointer(state, choice) {
    if (choice.index === state.index) {
      return colors.cyan(colors.symbols.pointer);
    }
    return ' ';
  },
  indicator(state, choice) {
    if (choice.enabled) {
      return colors.cyan(state.symbols.radio.on);
    }
    return colors.gray(state.symbols.radio.off);
  }
});

prompt.run()
  .then(answer => console.log('Answer:', answer))
  .catch(console.error);
```

**Comment by mikeerickson** [comment]
awesome, thanks!

**Comment by mikeerickson** [comment]
works like a charm, thank you very much ;-)

**Comment by doowb** [comment]
No problem. I'm glad that's what you were looking for!
