### ISSUE TITLE
Repetition of the same set of questions

### ISSUE THREAD

**Issue by Aeonrush** [enquirer/enquirer#7]
Hi
I write CLI for my little deploy tool, it based on [shipit](https://github.com/shipitjs/shipit), and I want to configure [`staging` section](https://github.com/shipitjs/shipit#example-shipitfilejs), but it involves a repetition of the same set of questions until you say 'no'.
How I can manage this with `enquirer`?

**Comment by jonschlinkert** [comment]
yikes, really sorry I missed this question. I believe Nov. was when I had a bad cold for a couple of weeks. apologies. 

Did you ever get this resolved? I don't blame you if you went in a different direction, but I'd be happy to help if you still have questions. (shipit is awesome btw)

**Comment by Aeonrush** [comment]
Hi
No, I'm not resolved this problem 😄

**Comment by doowb** [comment]
@Aeonrush I've been working on features and fixing bugs throughout `enquirer`. I can take a look at this and see if it's something we can add to enquirer or make a plugin for.

Do you have a code example of how you'd like to use this?

**Comment by jonschlinkert** [comment]
I believe this was resolved, I'm going to close but please feel free to reopen or create a new issue if you're still having problems.
