### ISSUE TITLE
Select prompt doesn't use initial value from function

### ISSUE THREAD

**Issue by renarsvilnis** [enquirer/enquirer#71]
When the initial value of a select prompt is a function, the returned value isn't used. But validated that the `initial` function gets called.

`enquirer 2.0.7`

**Not working:**

```js
{
    name: 'type',
    message: 'Article type:',
    type: 'select',
    choices: ['article', 'video'],
    initial: () => 'video'
}
```

**Working:**

```js
{
    name: 'type',
    message: 'Article type:',
    type: 'select',
    choices: ['article', 'video'],
    initial: 'video'
}
```

**Comment by jonschlinkert** [comment]
Thanks for creating an issue to let us know! Marking as a bug.
