### ISSUE TITLE
Confirm prompt initial not supporting functions

### ISSUE THREAD

**Issue by renarsvilnis** [enquirer/enquirer#78]
Hi,
found out that confirm promt and all "boolean" type prompts doesn't support intial values as functions or async functions.

```javascript
{
    type: 'confirm',
    name: 'confirmRecord',
    message: 'Confirm record:',
    initial: () => {
      // ... business logic that verifies stuff
      return true;
    }
};
```

Also another related feature request. I'm rewriting a cli app from inquirer to enquirer and noticed a feature missing. Could initial function recieve answers or some kind of context from previous questions? Similar as [`when`](https://github.com/SBoudrias/Inquirer.js/#objects) option in inquirer.

As a use case would be the snippet above. I want to pretty-print a "formatted" json object from the answers before asking the confirmation.

Right now as a workaround I manually manage the previous answers in a "shared" module.

**Comment by jonschlinkert** [comment]
Closing I think this was fixed in v2.0.9. However if you're still having problems with this please reopen so we can get it fixed. Thanks for creating an issue!
