### ISSUE TITLE
Feature Suggestion: Skipping a question on condition

### ISSUE THREAD

**Issue by TylorS** [enquirer/enquirer#8]
I'm building a series of command-line related tools and have been really please to run across this project. Previously I have been using `inquirer`, but have felt its weight and design decisions don't suit my goals too well. However one useful feature it has that is currently not supported here is the ability to skip a question based on previous answers.

```
enquirer.ask([
  {
    type: 'list',
    name: 'name',
    message: 'question?',
    // new - a function that returns a boolean value on whether or not to ask a question
    when: function (answers) {
       return answers.x === 'yes'
    })
  }
])
```

I've run into this need at least once building a interface for building commit messages (think [commitizen](https://github.com/commitizen/cz-cli)) where you need to ask additional questions if a commit represents a breaking change.

**Comment by tunnckoCore** [comment]
I believe it is possible and it may be not documented, or it is documented in some underlying building blocks. But also I can be in mistake with `question-cache`, I'll recheck.

**Comment by TylorS** [comment]
Thanks @tunnckoCore! I couldn't find any documentation for it. Closing.

**Comment by tunnckoCore** [comment]
What about something like

```js
var question = enquirer.question({
  name: 'color',
  message: 'What is your favorite color?',
  default: 'blue'
})
question.when = function when (answers) {
  // `this` context is the instance of promp-question/prompt-base
  // stuff.. and believe you will have access to `.filter` method too
}
```

**Comment by tunnckoCore** [comment]
@TylorS I don't think we should close it, cuz it is reasonable currently. And will be as remainder that there is a bug in prompt-base.

**Comment by doowb** [comment]
@TylorS what error are you getting? I tried this and it seems to be working.

**Comment by TylorS** [comment]
@doowb I'm not getting any error, I just couldn't find the related documentation to achieve this behavior.

@tunnckoCore Its working for me as well.

**Comment by jonschlinkert** [comment]
> I just couldn't find the related documentation to achieve this behavior.

thanks for the reminder, I'll create a new issue and link to this
