### ISSUE TITLE
Add the possibility to localize confirm prompts

### ISSUE THREAD

**Issue by AlCalzone** [enquirer/enquirer#80]
Confirm prompts are hardcoded to use <kbd>y</kbd> and <kbd>n</kbd>. In order to localize them, it would be nice if we could configure which keys result in `true` and which result in `false`.

**Comment by AlCalzone** [comment]
I'll try that out, thanks. I just found https://github.com/enquirer/enquirer/blob/master/lib/prompts/confirm.js and figured that the keys are hardcoded. Seems I got to take a look at the examples.

**Comment by jonschlinkert** [comment]
> figured that the keys are hardcoded

Almost everything in Enquirer can be customized or overridden. You can also update the `default` value (the "hint" that looks like this: `(Y/n)`) using similar logic to what I did in the last example:

```js
{
  name: 'apples',
  message: 'How do you like these apples?',
  onRun() {
    this.isTrue = input => input === 'f';
    this.isFalse = input => input === 't';
    this.default = 'Whatever you want';
  }
}
```

**Comment by AlCalzone** [comment]
I'm getting there, but not quite yet. I defined a function to wrap my questions, because extending existing classes resulted in some errors regarding `new`:
```ts
function localize(question: any) {
	return {
		...question,
		onRun() {
			this.isTrue = (input: string) => input === "j";
			this.isFalse = (input: string) => input === "n";
			this.default = question.initial ? "(J/n)" : "(j/N)";
		},
	};
}

// ...

const questions = [
	// ...
	localize({
		type: "confirm",
		name: "really",
		message: "Wirklich?",
		initial: false,
	}),
];
```

The CLI now shows `"Wirklich? (y/N)"` and switches to `"Wirklich? (j/N)"` **after** I make my choice.

**Comment by jonschlinkert** [comment]
That's a bug. I'll get it fixed and push up a patch. I'll also make sure it's easier to define that value properly on the options. Thanks for working through this with me.

**Comment by alcuadrado** [comment]
I couldn't find a way to localize the initial value formatting either. My prompt looks like this:

```? Message (Y/n) › true```

Displaying `true` instead of `Y` is confusing.

**Comment by jonschlinkert** [comment]
@alcuadrado you should be able to customize that pretty easily using `format()` on the options (question object).

```js
format() {
  return this.value === true ? 'Ja' : 'Nein';
}
```

You conditionally style the value as well (`this.styles` is an object with a handful of semantically named styles, to allow you to easily override colors and keep a consistent palette throughout the prompt):

```js
format() {
  let value = this.value === true ? 'Ja' : 'Nein';
  if (this.state.submitted === true) {
    return this.styles.info(value);
  }
  return value;
}
```

Working on a fix for this now. Any special requests? If you have ideas for improvements that don't require breaking changes I can squeeze those in any time, or there would be breaking changes just create a new issue with your ideas and we'll consider them for the next release.

**Comment by jonschlinkert** [comment]
I just pushed up some change that also allow the following:

```js
const { prompt } = require('enquirer');

prompt({
  type: 'confirm',
  name: 'really',
  message: 'Wirklich?',
  initial: 'j',
  default: '(J/n)',
  isTrue(input) {
    return input.toLowerCase() === 'j';
  },
  isFalse(input) {
    return input.toLowerCase() === 'n';
  }
})
  .then(console.log)
  .catch(console.log);
```

Hopefully this makes it a little easier.

**Comment by alcuadrado** [comment]
Thanks for this update @jonschlinkert!

I'm getting a new error now. I create my confirmation prompts with this function:

```js
function createConfirmationPrompt(name: string, message: string) {
  return {
    type: "confirm",
    name,
    message,
    initial: "y",
    default: "(Y/n)",
    isTrue(input: string) {
      return input.toLowerCase() === "y";
    },
    isFalse(input: string) {
      return input.toLowerCase() === "n";
    }
  };
}
```

And getting:

```
(node:9025) UnhandledPromiseRejectionWarning: TypeError: input.toLowerCase is not a function
    at ConfirmPrompt.isTrue (/Users/pato/projects/buidler/src/cli/project-creation.ts:179:20)
    at ConfirmPrompt.cast (/Users/pato/projects/buidler/node_modules/enquirer/lib/types/boolean.js:30:17)
    at ConfirmPrompt.render (/Users/pato/projects/buidler/node_modules/enquirer/lib/types/boolean.js:67:35)
    at <anonymous>
(node:9025) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

I think that isTrue is being called twice, and the second time it receives the already casted boolean.

**Comment by alcuadrado** [comment]
Wouldn't that result in `"true"` being compared against '"y"' and fail?

**Comment by jonschlinkert** [comment]
Yes, anything that isn't `y` would fail, since that's how you have it defined in your custom code. Isn't that correct? The prompt itself allows `true` or `y`, but your code overrides that. Maybe I'm missing something, I'll look at the code again...

**Comment by alcuadrado** [comment]
I'm not that familiar with the codebase, but two things draw my attention:

* I'd naturally expect [`#render`](https://github.com/enquirer/enquirer/blob/master/lib/types/boolean.js#L55) to be pure (at least conceptually), but it modifies [`this.value`](https://github.com/enquirer/enquirer/blob/master/lib/types/boolean.js#L67).
* [`#initialize`](https://github.com/enquirer/enquirer/blob/master/lib/types/boolean.js#L14) assigns `input` when no input is available.

At first glance it seems that these changes would solve this issue, as I'm pretty confident that these are the sources of the double casting:

* Not setting `input` on initialization. `Prompt` [already handles this](https://github.com/enquirer/enquirer/blob/master/lib/prompt.js#L414).

* Not setting `this.value` on render. That seems to be just an optimization. Just use `this.value` [here](https://github.com/enquirer/enquirer/blob/master/lib/types/boolean.js#L67)
