### ISSUE TITLE
How can I remove the underline

### ISSUE THREAD

**Issue by mikeerickson** [enquirer/enquirer#81]
Hey there

I am curious, is it possible to remove the underline for the current item in `multiselect`

![image](https://user-images.githubusercontent.com/183153/49258144-47a93080-f3e9-11e8-9884-b92f4cc21346.png)

I assume it will be here, but I dont see where the underline is set (maybe it is default_

```js
  ...
  indicator(state, choice) {
    return choice.enabled 
      ? colors.cyan(state.symbols.radio.on) 
      : colors.gray(state.symbols.radio.off);
  }
  ...
```

**Comment by doowb** [comment]
@mikeerickson there is a [style called heading](https://github.com/enquirer/enquirer/blob/9687a592e3b9465984c147bd5ac849a3444efe57/lib/styles.js#L42-L44) that you can override using the options like this:

```js
styles: {
  heading(msg) {
    return this.primary(msg);
  }
}
```

The default for `heading` is `this.primary.underline(msg)`, so this is just removing the `underline`.

> I assume it will be here, but I dont see where the underline is set

BTW... the part that you're referencing is the `indicator` which are the circles in your screenshot.

**Comment by mikeerickson** [comment]
@doowb Ya, I was mistaken about `indicator`  Thanks for the information above, I had found it in the source code where this is set and was in the process of tracking down the heading information you referenced above.

In the `lib/styles.js` file

```js
  get heading() {
    return this.primary.underline;
  },
```

**Comment by mikeerickson** [comment]
@doowb Now I will try and figure out how these values can be changed in the API. I am sure there is a way, just need to track it down.

**Comment by mikeerickson** [comment]
@jonschlinkert Is this something that can be changed?

**Comment by doowb** [comment]
> Now I will try and figure out how these values can be changed in the API

Do you mean when you extend a class?

**Comment by mikeerickson** [comment]
@doowb No, I am referring to changing from the API (if possible).  I have temporarily changed the source, but that is not an ample long term solution, as it will only survive until next update before I have to reapply.

**Comment by mikeerickson** [comment]
I am thinking it would be configured here

![image](https://user-images.githubusercontent.com/183153/49261496-5860a300-f3f7-11e8-910f-5b41b6138e72.png)

**Comment by doowb** [comment]
> am thinking it would be configured here

Oh, I might have been clear... the snippet that I put above is what you would put right there to override the header style:

```js
const questions = {
  type: 'multiselect',
  name: 'recipes',
  message: 'Select desired recipe(s) you wish to install:',
  styles: {
    heading(msg) {
      return this.primary(msg);
    }
  },
  choices,
  pointer(state, choice) { ... },
  indicator(state, choice) { ... }
```

**Comment by mikeerickson** [comment]
@doowb Ah, excellent. I thought you were referring to where it was located in the source code.  I applied what you outlined above and it works like a charm

**Comment by doowb** [comment]
Awesome! I'm glad it's working 😄

**Comment by jonschlinkert** [comment]
Or you can just do:

```js
  styles: {
    heading: colors.cyan // or whatever color you want
  }
```

**Comment by mikeerickson** [comment]
@jonschlinkert and @doowb  It seems this has stopped working with the recent 2.2.0 update?

Here is my code

```
const { prompt } = require("enquirer");
const colors = require("ansi-colors");

const questions = {
  type: "multiselect",
  message: "Selecting item, still shows underline:",
  choices: ["item1", "item2", "item3"],
  styles: {
    heading: colors.cyan // this used to remove underline as noted in replies
  },
  pointer(state, choice) {
    return choice.index === state.index ? colors.cyan.bold(colors.symbols.pointer) : " ";
  },
  indicator(state, choice) {
    return choice.enabled ? " " + colors.green("●") : " " + colors.gray("o");
  }
};

prompt(
  [questions],
  result => {
    console.log(result);
  },
  err => {
    console.error(err);
  }
);
```

Here is how it displays (notice, the highlighted item still has underline)

![image](https://user-images.githubusercontent.com/183153/50059784-29a93300-0140-11e9-9ce3-a2bef8921fdb.png)

If you want me to create a new issue, I can do that but figured I would just comment here first
