### ISSUE TITLE
Allow select on enter in multiselect (if nothing checked)

### ISSUE THREAD

**Issue by whitecolor** [enquirer/enquirer#84]
Currently in `multiselect` if nothing is checked you stay on some option and press enter result is an empty list. It would be good to have an option for prompt so that pressing enter on the element if nothing else checked would select it. 

This was a behavior in `inquirer` I used to. And it is quite convenient when you want to treat multiselect as a usual list but with multi-select option.

I mean that this behaviour should not (may not) be default in the package, but could be allowed as option.

**Comment by jonschlinkert** [comment]
IMHO, if a choice isn't checked the user would be surprised at the outcome you're describing. But I also think that you ought to be able to do this if it's what you need. You might be able to do this through options/events or overriding prompt methods... I'll play around with the code and see how hard it is, or if we need to make this easier to do.

In the meantime, wouldn't the `initial` option accomplish what you want? Or do you specifically want the item at the current pointer index to be selected when the user submits?

**Comment by whitecolor** [comment]
> In the meantime, wouldn't the initial option accomplish what you want? Or do you specifically want the item at the current pointer index to be selected when the user submits?

Initial probably won't work, I want just to go to need item and press just `enter` to choose it, not `space + enter`.

**Comment by mikeerickson** [comment]
I can see the desire for this as well, I have hit this issue many times today when testing my multi select.  If not selecting the highlighted item, how about not allowing enter to “close” list if at least one item has not been selected

**Comment by mikeerickson** [comment]
In my case, I want user to be able to select one or more items.  But, your statement about controlling via `validate` will suffice for my use case.

**Comment by whitecolor** [comment]
I believe using `validate` would work.

**Comment by jonschlinkert** [comment]
Okay, I'll still keep this open to solicit more feedback, in case someone has an idea on how to do this more idiomatically.

**Comment by jonschlinkert** [comment]
I just pushed up changes that allow you to do the following:

```js
const { MultiSelect } = require('enquirer');

const prompt = new MultiSelect({
  name: 'example',
  message: 'Pick one or more colors',
  choices: [
    { name: 'aqua', value: '#00ffff' },
    { name: 'black', value: '#000000' },
    { name: 'blue', value: '#0000ff' },
    { name: 'fuchsia', value: '#ff00ff' },
    { name: 'green', value: '#008000' },
    { name: 'lime', value: '#00ff00' },
    { name: 'maroon', value: '#800000' },
    { name: 'navy', value: '#000080' }
  ],
  onSubmit() {
    if (this.selected.length === 0) {
      this.enable(this.focused);
    }
  }
});

prompt.run()
  .then(answer => console.log('Answer:', answer))
  .catch(console.error);
```

- `this.focused` is the choice at the current pointer index
- `this.enable()` takes a choice and enables it. 

The `onSubmit` function is called first thing when the user submits.
