### ISSUE TITLE
Feature request: Pre-/Post-validate transforms

### ISSUE THREAD

**Issue by AlCalzone** [enquirer/enquirer#85]
As I figured out from looking at the code, the user input goes through the following stages:

* `validate` - tests if the input is valid
* `format` - formats the input before writing it to the console
* `result` - formats the input again before saving it in the results

For a project of mine, it would be nice if it was possible to transform the input before validation occurs. E.g. remove some part of a string that is tolerated, but not necessary.

Oh, and documentation for that "result pipeline" would be nice.

**Comment by jonschlinkert** [comment]
> For a project of mine, it would be nice if it was possible to transform the input before validation occurs. E.g. remove some part of a string that is tolerated, but not necessary.

I went back and forth on this. What if we added support for `transform` to do what you're suggesting? 

> documentation for that "result pipeline" would be nice.

Lots of documentation is on the way! I've spent many hours on Enquirer docs over the past couple of weeks!

**Comment by jonschlinkert** [comment]
Actually, couldn't you just accomplish what you need by calling the `result()` function inside the validate function? Or by using other logic in the validate function that accomplishes the same goal?

**Comment by AlCalzone** [comment]
But that doesn't change the input value outside of the validate method, or does it?

**Comment by jonschlinkert** [comment]
> The other approach seems more straightforward IMO.

Meaning a `transform` function? I'm open to it if that's what you meant.

**Comment by AlCalzone** [comment]
Yes 🙂

**Comment by AlCalzone** [comment]
I'm unsure how d599f71 fixes this. Can you give me a hint please?

**Comment by AlCalzone** [comment]
I think I misunderstood `onSubmit` - thanks. I though it was just there to allow selecting stuff in unselected multiselects.

**Comment by AlCalzone** [comment]
@jonschlinkert I just came around to trying this. In the `onSubmit` callback, I overwrite `this.value` with the transformed value. However, after that (inside `validate` and after the prompt returns), the prompt still has the original value.

Either the method is not working as I thought or I am doing something wrong. How would I realize the following?

1. Ask user for text input, e.g. "foo.bar"
2. Transform that input and continue as if the user had entered the result of the transformation directly, e.g. "bar"
3. Run some validation logic (with the previously transformed value "bar")
4. If the validation succeeded, return "bar" as the prompt value.
