### ISSUE TITLE
What does `value` properties provide in multiselect

### ISSUE THREAD

**Issue by mikeerickson** [enquirer/enquirer#86]
I am trying to figure out what the `value` property provides when multiselect prompt?

```
const { MultiSelect } = require("enquirer");

const prompt = new MultiSelect({
  name: "value",
  message: "Pick what you want",
  limit: 7,
  choices: [
    { name: "test", message: "test message", value: "value" },
    { name: "test2", message: "test message2", value: "value2" },
    { name: "test3", message: "test message3", value: "value3" },
  ]
});

prompt
  .run()
  .then(answer => console.log(answer))
  .catch(console.error);
```
When I make the selection, it returns an array of `answers` which contains the entries from `name` property.

**Comment by jonschlinkert** [comment]
`value` is an optional field, you can omit that field if you're not using it.  You can also change the result by defining a `result()` function on the options. 

Also, there are several other types of array prompts, and the conventions for the choice objects were designed to cover a number of use cases.

**Comment by mikeerickson** [comment]
Am I correct in assuming that the `value` field is not used for `multiselect` type and that the answers array will always contain the data in the `name` field?

**Comment by jonschlinkert** [comment]
I think you're correct, it's not used by default. I'm pretty sure it was used initially and we changed it to return `name` instead since that allows you to easily get the values. However, if we return `value`, it's slightly more tedious to get the names.

**Comment by mikeerickson** [comment]
Works for me, just making sure.
