### ISSUE TITLE
Editor Prompt

### ISSUE THREAD

**Issue by sebald** [enquirer/enquirer#87]
Hey! Is there any plan to implement an `EditorPrompt` like: https://github.com/SBoudrias/Inquirer.js/blob/master/packages/inquirer/lib/prompts/editor.js

Or does anyone have written that prompt already? Just wanted to ask before I am trying to roll my own 😄

**Comment by sebald** [comment]
Never mind ... 🤦‍♂️

https://github.com/enquirer/prompt-editor

**Comment by zkochan** [comment]
That package seems to support only pre-v2 enquirer. How to have an editor prompt with the latest enquirer?
