### ISSUE TITLE
docs: need docs for `when` method

### ISSUE THREAD

**Issue by jonschlinkert** [enquirer/enquirer#9]
related #8

**Comment by leebenson** [comment]
Is there still being actively maintained?

Not a criticism, just a genuine question. I don't mind digging into source code to find the answers, but seeing some of these 'hidden' features land in docs would, IMO, give users more confidence to adopt a library like this as an alternative to Inquirer.

**Comment by jonschlinkert** [comment]
Is what still being maintained? This library has more activity than you do, are you stil being maintained?

**Comment by jonschlinkert** [comment]
https://github.com/enquirer/prompt-base#run

**Comment by leebenson** [comment]
Apologies if it caused offence; it was a genuine question. It seems like the doc is out of sync with features, and this issue has been open over 6 months without resolution. In a world where 90% of libs lose steam, it's a pretty common question to ask.

**Comment by jonschlinkert** [comment]
This feature was created by me, a maintainer of the project. Not a user. 

> In a world where 90% of libs lose steam, it's a pretty common question to ask.

https://github.com/jonschlinkert/idiomatic-contributing#dont

**Comment by leebenson** [comment]
> This question was created by me, a maintainer of the project. Not a user.

I get that. But you created it 6 months ago. If the docs haven't been updated within the last half-year, to me (as a new user of your lib, seeing it for the very first time) that doesn't bode well to build stuff on top of this, if even if the docs aren't finished.

The README doesn't mention `when` _at all_. A better answer would be an ETA for finishing docs.

> https://github.com/jonschlinkert/idiomatic-contributing#dont

You wrote that, not me. As a fellow library author, I wholeheartedly disagree that asking if a project is being maintained is offensive. Putting stuff out there for others to use means being open to others to questioning whether its a good fit for their projects. Again, it was a genuine question; plenty of maintainers get bored/busy/hired and drop projects -- I've done it myself, and would happily admit when that's the case.

What's wrong with asking if that's the case here, if the docs aren't complete?

**Comment by jonschlinkert** [comment]
> (as a new user of your lib, seeing it for the very first time) that doesn't bode well to build stuff on top of this, if even if the docs aren't finished.

You sound like you jump to conclusions and don't do research. Should we feel like we're losing someone who would have been valuable?

> I wholeheartedly disagree that asking if a project is being maintained is offensive.

Then you are not someone we want using our projects.
