### ISSUE TITLE
Confirm prompt with initial value always returns true

### ISSUE THREAD

**Issue by mikeerickson** [enquirer/enquirer#91]
I am using the example from

https://github.com/enquirer/enquirer/blob/master/examples/confirm/option-initial-true.js

when executing, it always returns `true` in the answer resolve?  Can someone please run a quick test and see if they receive actual negative value.

Note:  If I run without an inital value, the response is correct (but it defaults to false, I need it to default to true, hence the reason for using the `initial` property)

**Comment by jonschlinkert** [comment]
I can confirm that this was happening, and I thought I pushed up a fix! Apparently, I didn't! Thanks for creating the issue, I'll get this, and a few other patches, pushed up ASAP!

**Comment by mikeerickson** [comment]
@jonschlinkert Awesome, thanks a bunch.  please let me know when it has been pushed so I can update.

**Comment by jonschlinkert** [comment]
While I'm working on the confirm prompt, is there anything else you can think of that we should consider doing (without breaking changes, so I can get it finished quickly) to improve it?

**Comment by mikeerickson** [comment]
@jonschlinkert The only other issue I have run into thus far, is the following

https://github.com/enquirer/enquirer/issues/92
