### ISSUE TITLE
Confusion with MultiSelect

### ISSUE THREAD

**Issue by mikeerickson** [enquirer/enquirer#92]
I am using the following code snippet to display a multiselect list.  I only want to allow one item to be selected, so I set the `limit` property to 1 (assuming that is the correct choice).  However, doing this, it only displays one of the `choices`

I would like to display all choices, but only allow user to select one of them

```js
const { MultiSelect } = require("enquirer");

const prompt = new MultiSelect({
  name: "value",
  message: "Pick what you want",
  limit: 1,
  choices: [
    { name: "test", message: "test message", value: "value", hint: "hint" },
    { name: "test2", message: "test message2", value: "value2", hint: "hint2" },
    { name: "test3", message: "test message3", value: "value3", hint: "hint3" }
  ]
});

prompt
  .run()
  .then(answer => console.log(answer))
  .catch(console.error);
```

**Comment by jonschlinkert** [comment]
How about if we add support for `maxSelected`? I don't think that would even be a breaking change. 

(fwiw I'm going to delete the cross reference you did on the other issue, so that it keeps the issues cleaner for anyone who looks for these answers in the future. no big deal, just wanted to mention it).

**Comment by mikeerickson** [comment]
`maxSelected` works for me and agree that it would be a clean implementation. I figured I could do validation on event, but having it as part of API is indeed best

**Comment by jonschlinkert** [comment]
Done! Here is a quick and dirty example. I added a `format()` function just to show how you can provide additional information to the user if you wish. 

![multiselect-option-maxselected](https://user-images.githubusercontent.com/383994/50048178-4d626f80-0093-11e9-9597-adc6f4c6a906.gif)

Doing unit tests now.

**Comment by jonschlinkert** [comment]
btw, have you used the `fn+up`/`fn+down` combos with any of the choices prompts yet? (pageUp/pageDown on windows). I don't think it's well documented but thought you might find it handy.

**Comment by mikeerickson** [comment]
@jonschlinkert Thanks for the update, I have applied it in my app and all is well in the world 👍
