### ISSUE TITLE
Brainstorm:  Strategy for show series of prompts

### ISSUE THREAD

**Issue by mikeerickson** [enquirer/enquirer#93]
Curious what you all have done to display a series of prompts.  My current interface is to show each prompt in an `async` function.   Basically, a series of synchronous calls is really what I need to implement.

```js

async function inputPrompt(...) {
  let result = await prompt(...)
  return result;
}

let fname = inputPrompt("enter fname");
let lname = inputPrompt("enter lname");
let email = inputPrompt("enter email");
```

**Comment by jonschlinkert** [comment]
There are several approaches you can take depending on preferences and what you need. Before I recommend something, are you able to show more of your code? Ideally a link to your code so I can see how you want to define everything, or just paste some code here or show a longer example to help me understand what you want to achieve.

**Comment by mikeerickson** [comment]
I will post something later this evening or tomorrow, away from computer now (wife home from work so ...) 🤓

**Comment by mikeerickson** [comment]
@jonschlinkert Here is a [quick](https://github.com/mikeerickson/equirer-sample) and dirty repo of what I am trying to accomplish as best possible.  This version is just using standard Promises out of the box.   I have also constructed something using `Async/Await` in the real application, but the requirements are the same.

https://github.com/mikeerickson/equirer-sample

**Comment by jonschlinkert** [comment]
@mikeerickson, the way the prompts are defined currently, they will all try to run simultaneously, not in series. To get those to work the way you want (without overlapping each other), here are some approaches you can take:

## 1. Use `{ prompt }`

Re-write the questions to use enquirer's static `prompt` method. This takes an array of "questions" (or a single question), and it does what I think you're trying to accomplish.

```js
prompt([
  {
    name: 'first_name',
    messsage: 'What is your first name?'
  },
  {
    name: 'last_name',
    messsage: 'What is your last name?'
  },
  {
    name: 'email',
    messsage: 'What is your email address?'
  }
])
  .then(answers => {
    console.log(answers);
  })
  .catch(console.log);
```

## 2. async-await each prompt

If there is a good reason for keeping the prompts separate, wrap everything in an `async` function, and await each prompt. 

```js
(async() => {

if (fname === "") {
  const fnamePrompt = new Input({
    message: "Please supply first name?"
  });

  await fnamePrompt
    .run()
    .then(answer => console.log("First Name:", answer))
    .catch(console.log);
}

if (lname === "") {
  const lastNamePrompt = new Input({
    message: "Please supply last name?"
  });

  await lastNamePrompt
    .run()
    .then(answer => console.log("Last Name:", answer))
    .catch(console.log);
}

if (email === "") {
  const emailPrompt = new Input({
    message: "Please supply email?"
  });

  await emailPrompt
    .run()
    .then(answer => console.log("Email:", answer))
    .catch(console.log);
}

})().catch(console.error);
```

This is not ideal since, in reality, you would want to propagate errors and answers from these prompts to your application. It would be better to wrap the whole thing in a `new Promise()` to handle errors and answers.

**Comment by mikeerickson** [comment]
@jonschlinkert Thanks for the recommendations.  I can see what you are saying, this is clear enough for my implementation needs.  I will give it  a whirl and let you know if I have any issues.

**Comment by mikeerickson** [comment]
@jonschlinkert works like a charm!  I went with the array of questions as you suggested and it will do EXACTLY what I want.   And, I learned a couple things along the way.

```js
const { prompt } = require("enquirer");

prompt([
  {
    type: "input",
    name: "first_name",
    message: " What is your first name?"
  },
  {
    type: "select",
    name: "last_name",
    message: " What is your last name?",
    choices: ["Erickson", "Asoau"]
  },
  {
    type: "input",
    name: "email",
    message: " What is your email address?"
  },
  {
    type: "multiselect",
    name: "pkg",
    choices: ["npm", "yarn"],
    maxSelected: 1,
    limit: 2,
    hint: "Make sure you don't mix tools",
    initial: "yarn",
    message: " Which package manager would you like to use?"
  }
])
  .then(answers => {
    console.log(answers);
  })
  .catch(console.log);
```

![image](https://user-images.githubusercontent.com/183153/50058278-d8db0f80-012a-11e9-8665-fd067a612654.png)
